using System.Collections.Generic;

namespace SimpleDPI;

public static class Localization
{
    public static string CurrentLanguage = "tr";

    public static readonly Dictionary<string, Dictionary<string, string>> Dictionaries = new()
    {
        { "tr", new Dictionary<string, string> {
            { "Status_Off", "Kapalı" }, { "Status_Running", "Çalışıyor" },
            { "Settings_Title", "Ayarlar" }, { "Profile_Title", "Güç Profili" },
            { "Profile_Tip", "Paketlerin DPI'a karşı nasıl parçalanacağını belirler. Standart 5 en dengelisidir." },
            { "Dns_Title", "Şifreli DNS" }, { "Dns_Tip", "İSS tabanlı DNS manipülasyonlarını engeller." },
            { "Advanced_Title", "Filtreler" }, { "Quic_Label", "QUIC Kapat" }, { "Quic_Tip", "UDP yerine TCP kullanımına zorlar." },
            { "Reverse_Label", "Ters Parçalanma" }, { "Reverse_Tip", "HTTPS için farklı paket sırası." },
            { "Manual_Btn", "Manuel" }, { "Reset_Btn", "Sıfırla" }, { "Apply_Btn", "Uygula" },
            { "Ask_Exit", "Ne yapmak istersiniz?" }, { "Exit_Exit", "Çıkış" }, { "Exit_Hide", "Gizle" }, { "Exit_Cancel", "İptal" },
            { "Toast_Applied", "✓ Kaydedildi!" }, { "Language_Title", "Diller" },
            { "Blur_Label", "Saydamlık" }, { "Boot_Label", "Başlangıçta Başlat" }, { "AutoStart_Label", "Otomatik Başlat" },
            { "Unsaved_Msg", "Kaydedilmemiş ayarlar var!" }, { "Discard_Btn", "At" },
            { "About_Title", "Hakkında" }, { "Tray_Show", "Göster" }, { "Tray_Exit", "Kapat" },
            { "Tray_Toggle", "Mod Değiştir" },
            { "Reset_Msg", "Tüm ayarlar sıfırlansın?" }, { "Reset_Confirm", "Sıfırla" },
            { "Status_Crashed", "Hizmet Kapandı" }
        }},
        { "en", new Dictionary<string, string> {
            { "Status_Off", "Off" }, { "Status_Running", "Running" },
            { "Settings_Title", "Settings" }, { "Profile_Title", "Profile" },
            { "Profile_Tip", "Defines fragmentation. Mode 5 is balanced." },
            { "Dns_Title", "Encrypted DNS" }, { "Dns_Tip", "Bypasses ISP-level DNS manipulation." },
            { "Advanced_Title", "Filters" }, { "Quic_Label", "Disable QUIC" }, { "Quic_Tip", "Forces sites to use TCP." },
            { "Reverse_Label", "Reverse Fragment" }, { "Reverse_Tip", "Different packet order for HTTPS." },
            { "Manual_Btn", "Manual" }, { "Reset_Btn", "Reset" }, { "Apply_Btn", "Apply" },
            { "Ask_Exit", "Action?" }, { "Exit_Exit", "Exit" }, { "Exit_Hide", "Hide" }, { "Exit_Cancel", "Cancel" },
            { "Toast_Applied", "✓ Applied!" }, { "Language_Title", "Languages" },
            { "Blur_Label", "Blur Effect" }, { "Boot_Label", "Start on Boot" }, { "AutoStart_Label", "Auto-start" },
            { "Unsaved_Msg", "Unsaved changes!" }, { "Discard_Btn", "Discard" },
            { "About_Title", "About" }, { "Tray_Show", "Show" }, { "Tray_Exit", "Exit" },
            { "Tray_Toggle", "Toggle Mode" },
            { "Reset_Msg", "Reset everything?" }, { "Reset_Confirm", "Reset" },
            { "Status_Crashed", "Service Stopped" }
        }},
        { "ru", new Dictionary<string, string> {
            { "Status_Off", "Выкл" }, { "Status_Running", "Запущено" },
            { "Settings_Title", "Настройки" }, { "Profile_Title", "Профиль" },
            { "Profile_Tip", "Определяет фрагментацию. Режим 5 сбалансирован." },
            { "Dns_Title", "Шифрованный DNS" }, { "Dns_Tip", "Обходит манипуляции DNS провайдера." },
            { "Advanced_Title", "Фильтры" }, { "Quic_Label", "Откл. QUIC" }, { "Quic_Tip", "Принуждает сайты использовать TCP." },
            { "Reverse_Label", "Реверс фрагм." }, { "Reverse_Tip", "Другой порядок пакетов для HTTPS." },
            { "Manual_Btn", "Вручную" }, { "Reset_Btn", "Сброс" }, { "Apply_Btn", "Применить" },
            { "Ask_Exit", "Что сделать?" }, { "Exit_Exit", "Выйти" }, { "Exit_Hide", "Скрыть" }, { "Exit_Cancel", "Отмена" },
            { "Toast_Applied", "✓ Применено!" }, { "Language_Title", "Языки" },
            { "Blur_Label", "Эффект размытия" }, { "Boot_Label", "Автозагрузка" }, { "AutoStart_Label", "Автозапуск" },
            { "Unsaved_Msg", "Есть несохраненные изменения!" }, { "Discard_Btn", "Сбросить" },
            { "About_Title", "О программе" }, { "Tray_Show", "Показать" }, { "Tray_Exit", "Выход" },
            { "Tray_Start", "Режим: ВКЛ" }, { "Tray_Stop", "Режим: ВЫКЛ" },
            { "Reset_Msg", "Сбросить все настройки?" }, { "Reset_Confirm", "Сброс" }
        }},
        { "ar", new Dictionary<string, string> {
            { "Status_Off", "مغلق" }, { "Status_Running", "يعمل" },
            { "Settings_Title", "الإعدادات" }, { "Profile_Title", "الملف الشخصي" },
            { "Profile_Tip", "يحدد تجزئة الحزم. الوضع 5 هو الأكثر توازناً." },
            { "Dns_Title", "DNS مشفر" }, { "Dns_Tip", "يتجاوز تلاعب DNS الخاص بمزود الخدمة." },
            { "Advanced_Title", "الفلاتر" }, { "Quic_Label", "تعطيل QUIC" }, { "Quic_Tip", "يجبر المواقع على استخدام TCP." },
            { "Reverse_Label", "تجزئة عكسية" }, { "Reverse_Tip", "يستخدم ترتيب حزم مختلف لـ HTTPS." },
            { "Manual_Btn", "يدوي" }, { "Reset_Btn", "إعادة تعيين" }, { "Apply_Btn", "تطبيق" },
            { "Ask_Exit", "ماذا تريد أن تفعل؟" }, { "Exit_Exit", "خروج" }, { "Exit_Hide", "إخفاء" }, { "Exit_Cancel", "إلغاء" },
            { "Toast_Applied", "✓ تم التطبيق!" }, { "Language_Title", "اللغات" },
            { "Blur_Label", "تأثير الضباب" }, { "Boot_Label", "بدء مع النظام" }, { "AutoStart_Label", "تشغيل تلقائي" },
            { "Unsaved_Msg", "تعديلات غير محفوظة!" }, { "Discard_Btn", "تجاهل" },
            { "About_Title", "حول" }, { "Tray_Show", "إظهار" }, { "Tray_Exit", "خروج" },
            { "Tray_Start", "الوضع: يعمل" }, { "Tray_Stop", "الوضع: متوقف" },
            { "Reset_Msg", "إعادة تعيين كافة الإعدادات؟" }, { "Reset_Confirm", "تأكيد" }
        }},
        { "hi", new Dictionary<string, string> {
            { "Status_Off", "बंद" }, { "Status_Running", "चल रहा है" },
            { "Settings_Title", "सेटिंग्स" }, { "Profile_Title", "प्रोफ़ाइल" },
            { "Profile_Tip", "पैकेट विखंडन निर्धारित करता है। मोड 5 संतुलित है।" },
            { "Dns_Title", "एन्क्रिप्टेड DNS" }, { "Dns_Tip", "ISP-स्तरीय DNS हेरफेर को बायपास करता है।" },
            { "Advanced_Title", "फ़िल्टर" }, { "Quic_Label", "QUIC अक्षम करें" }, { "Quic_Tip", "साइटों को TCP उपयोग करने के लिए मजबूर करता है।" },
            { "Reverse_Label", "रिवर्स फ्रैगमेंट" }, { "Reverse_Tip", "HTTPS के लिए अलग पैकेट क्रम।" },
            { "Manual_Btn", "मैनुअल" }, { "Reset_Btn", "रीसेट" }, { "Apply_Btn", "लागू करें" },
            { "Ask_Exit", "क्या करना है?" }, { "Exit_Exit", "निकास" }, { "Exit_Hide", "छिपाएँ" }, { "Exit_Cancel", "रद्द करें" },
            { "Toast_Applied", "✓ लागू किया गया!" }, { "Language_Title", "भाषाएँ" },
            { "Blur_Label", "धुंधला प्रभाव" }, { "Boot_Label", "बूट पर शुरू" }, { "AutoStart_Label", "ऑटो-स्टार्ट" },
            { "Unsaved_Msg", "अपरिवर्तित परिवर्तन!" }, { "Discard_Btn", "छोड़ें" },
            { "About_Title", "बारे में" }, { "Tray_Show", "दिखाएं" }, { "Tray_Exit", "निकास" },
            { "Tray_Start", "स्थिति: चालू" }, { "Tray_Stop", "स्थिति: बंद" },
            { "Reset_Msg", "सब कुछ रीसेट करें?" }, { "Reset_Confirm", "रीसेट" }
        }},
        { "uk", new Dictionary<string, string> {
            { "Status_Off", "Вимкнено" }, { "Status_Running", "Працює" },
            { "Settings_Title", "Налаштування" }, { "Profile_Title", "Профіль" },
            { "Profile_Tip", "Визначає фрагментацію. Режим 5 найбільш збалансований." },
            { "Dns_Title", "Шифрований DNS" }, { "Dns_Tip", "Обходить маніпуляції DNS провайдера." },
            { "Advanced_Title", "Фільтри" }, { "Quic_Label", "Вимкнути QUIC" }, { "Quic_Tip", "Змушує сайти використовувати TCP." },
            { "Reverse_Label", "Реверс фрагм." }, { "Reverse_Tip", "Інший порядок пакетів для HTTPS." },
            { "Manual_Btn", "Вручну" }, { "Reset_Btn", "Скинути" }, { "Apply_Btn", "Застосувати" },
            { "Ask_Exit", "Дія?" }, { "Exit_Exit", "Вихід" }, { "Exit_Hide", "Сховати" }, { "Exit_Cancel", "Скасувати" },
            { "Toast_Applied", "✓ Застосовано!" }, { "Language_Title", "Мови" },
            { "Blur_Label", "Ефект розмиття" }, { "Boot_Label", "Автозапуск" }, { "AutoStart_Label", "Авто-старт" },
            { "Unsaved_Msg", "Незбережені зміни!" }, { "Discard_Btn", "Скинути" },
            { "About_Title", "Про програму" }, { "Tray_Show", "Показати" }, { "Tray_Exit", "Вихід" },
            { "Tray_Start", "Режим: УВІМК" }, { "Tray_Stop", "Режим: ВИМК" },
            { "Reset_Msg", "Скинути все?" }, { "Reset_Confirm", "Скидання" }
        }},
        { "zh", new Dictionary<string, string> {
            { "Status_Off", "已停止" }, { "Status_Running", "运行中" },
            { "Settings_Title", "设置" }, { "Profile_Title", "模式选择" },
            { "Profile_Tip", "数据包分片方式，5 为推荐模式。" },
            { "Dns_Title", "加密 DNS" }, { "Dns_Tip", "绕过运营商 DNS 劫持。" },
            { "Advanced_Title", "进阶过滤" }, { "Quic_Label", "禁用 QUIC" }, { "Quic_Tip", "强制站点使用 TCP。" },
            { "Reverse_Label", "反向分片" }, { "Reverse_Tip", "针对 HTTPS 调整顺序。" },
            { "Manual_Btn", "手动控制" }, { "Reset_Btn", "重置" }, { "Apply_Btn", "应用" },
            { "Ask_Exit", "退出选项" }, { "Exit_Exit", "退出" }, { "Exit_Hide", "在后台运行" }, { "Exit_Cancel", "取消" },
            { "Toast_Applied", "✓ 已应用!" }, { "Language_Title", "多语言" },
            { "Blur_Label", "模糊特效" }, { "Boot_Label", "开机自启" }, { "AutoStart_Label", "服务自启" },
            { "Unsaved_Msg", "未保存更改!" }, { "Discard_Btn", "放弃" },
            { "About_Title", "关于" }, { "Tray_Show", "显示控制台" }, { "Tray_Exit", "完全退出" },
            { "Tray_Start", "状态: 开启" }, { "Tray_Stop", "状态: 关闭" },
            { "Reset_Msg", "恢复默认设置?" }, { "Reset_Confirm", "立即重置" }
        }},
        { "es", new Dictionary<string, string> {
            { "Status_Off", "Apagado" }, { "Status_Running", "Corriendo" },
            { "Settings_Title", "Ajustes" }, { "Profile_Title", "Perfil" },
            { "Profile_Tip", "Determina la fragmentación. El modo 5 es el más equilibrado." },
            { "Dns_Title", "DNS Cifrado" }, { "Dns_Tip", "Evita la manipulación DNS del ISP." },
            { "Advanced_Title", "Filtros" }, { "Quic_Label", "Desactivar QUIC" }, { "Quic_Tip", "Obliga a los sitios a usar TCP." },
            { "Reverse_Label", "Frag. Inversa" }, { "Reverse_Tip", "Diferente orden de paquetes para HTTPS." },
            { "Manual_Btn", "Manual" }, { "Reset_Btn", "Reset" }, { "Apply_Btn", "Aplicar" },
            { "Ask_Exit", "¿Qué hacer?" }, { "Exit_Exit", "Salir" }, { "Exit_Hide", "Ocultar" }, { "Exit_Cancel", "Cancelar" },
            { "Toast_Applied", "✓ ¡Aplicado!" }, { "Language_Title", "Idiomas" },
            { "Blur_Label", "Efecto de Desenfoque" }, { "Boot_Label", "Auto-arranque" }, { "AutoStart_Label", "Auto-inicio serv." },
            { "Unsaved_Msg", "¡Cambios sin guardar!" }, { "Discard_Btn", "Descartar" },
            { "About_Title", "Acerca de" }, { "Tray_Show", "Mostrar" }, { "Tray_Exit", "Salir" },
            { "Tray_Start", "Modo: ON" }, { "Tray_Stop", "Modo: OFF" },
            { "Reset_Msg", "¿Restablecer todo?" }, { "Reset_Confirm", "Confirmar" }
        }},
        { "fr", new Dictionary<string, string> {
            { "Status_Off", "Arrêté" }, { "Status_Running", "Actif" },
            { "Settings_Title", "Paramètres" }, { "Profile_Title", "Profil" },
            { "Profile_Tip", "Détermine la fragmentation. Le mode 5 est équilibré." },
            { "Dns_Title", "DNS Sécurisé" }, { "Dns_Tip", "Contourne le DNS du fournisseur." },
            { "Advanced_Title", "Filtres" }, { "Quic_Label", "Désactiver QUIC" }, { "Quic_Tip", "Force l'utilisation du TCP." },
            { "Reverse_Label", "Frag. Inverse" }, { "Reverse_Tip", "Utilise un ordre différent pour HTTPS." },
            { "Manual_Btn", "Manuel" }, { "Reset_Btn", "Réinitialiser" }, { "Apply_Btn", "Appliquer" },
            { "Ask_Exit", "Action?" }, { "Exit_Exit", "Fermer" }, { "Exit_Hide", "Masquer" }, { "Exit_Cancel", "Annuler" },
            { "Toast_Applied", "✓ Appliqué!" }, { "Language_Title", "Langues" },
            { "Blur_Label", "Effet de flou" }, { "Boot_Label", "Lancer au démarrage" }, { "AutoStart_Label", "Auto-démarrage" },
            { "Unsaved_Msg", "Modifications non sauvées!" }, { "Discard_Btn", "Annuler" },
            { "About_Title", "À propos" }, { "Tray_Show", "Afficher" }, { "Tray_Exit", "Quitter" },
            { "Tray_Start", "Mode: ON" }, { "Tray_Stop", "Mode: OFF" },
            { "Reset_Msg", "Réinitialiser tout?" }, { "Reset_Confirm", "Confirmer" }
        }},
        { "de", new Dictionary<string, string> {
            { "Status_Off", "Aus" }, { "Status_Running", "Aktiv" },
            { "Settings_Title", "Einstellungen" }, { "Profile_Title", "Profil" },
            { "Profile_Tip", "Bestimmt die Fragmentierung. Modus 5 ist ausgewogen." },
            { "Dns_Title", "Verschlüsseltes DNS" }, { "Dns_Tip", "Umgeht herkömmliche DNS-Manipulationen." },
            { "Advanced_Title", "Filter" }, { "Quic_Label", "QUIC deaktivieren" }, { "Quic_Tip", "Zwingt Websites zur Nutzung von TCP." },
            { "Reverse_Label", "Reverse Fragment" }, { "Reverse_Tip", "Andere Paketsequenz für HTTPS." },
            { "Manual_Btn", "Manuell" }, { "Reset_Btn", "Reset" }, { "Apply_Btn", "Anwenden" },
            { "Ask_Exit", "Aktion?" }, { "Exit_Exit", "Beenden" }, { "Exit_Hide", "Verbergen" }, { "Exit_Cancel", "Abbrechen" },
            { "Toast_Applied", "✓ Übernommen!" }, { "Language_Title", "Sprachen" },
            { "Blur_Label", "Glaseffekt" }, { "Boot_Label", "Auto-Start System" }, { "AutoStart_Label", "Auto-Dienststart" },
            { "Unsaved_Msg", "Ungespeicherte Änderungen!" }, { "Discard_Btn", "Verwerfen" },
            { "About_Title", "Über" }, { "Tray_Show", "Anzeigen" }, { "Tray_Exit", "Beenden" },
            { "Tray_Start", "Status: EIN" }, { "Tray_Stop", "Status: AUS" },
            { "Reset_Msg", "Alles zurücksetzen?" }, { "Reset_Confirm", "Säubern" }
        }},
        { "it", new Dictionary<string, string> {
            { "Status_Off", "Spento" }, { "Status_Running", "Attivo" },
            { "Settings_Title", "Impostazioni" }, { "Profile_Title", "Profilo" },
            { "Profile_Tip", "Determina la frammentazione. La modalità 5 è bilanciata." },
            { "Dns_Title", "DNS Cifrato" }, { "Dns_Tip", "Evita la manipolazione DNS del provider." },
            { "Advanced_Title", "Filtri" }, { "Quic_Label", "Disabilita QUIC" }, { "Quic_Tip", "Forza l'uso di TCP." },
            { "Reverse_Label", "Framm. Inversa" }, { "Reverse_Tip", "Sequenza diversa per HTTPS." },
            { "Manual_Btn", "Manuale" }, { "Reset_Btn", "Reset" }, { "Apply_Btn", "Applica" },
            { "Ask_Exit", "Cosa fare?" }, { "Exit_Exit", "Esci" }, { "Exit_Hide", "Nascondi" }, { "Exit_Cancel", "Annulla" },
            { "Toast_Applied", "✓ Applicato!" }, { "Language_Title", "Lingue" },
            { "Blur_Label", "Effetto Sfocatura" }, { "Boot_Label", "Avvio al boot" }, { "AutoStart_Label", "Avvio auto" },
            { "Unsaved_Msg", "Modifiche non salvate!" }, { "Discard_Btn", "Scarta" },
            { "About_Title", "Info" }, { "Tray_Show", "Mostra" }, { "Tray_Exit", "Esci" },
            { "Tray_Start", "Stato: ON" }, { "Tray_Stop", "Stato: OFF" },
            { "Reset_Msg", "Ripristina tutto?" }, { "Reset_Confirm", "Sì" }
        }},
        { "pt", new Dictionary<string, string> {
            { "Status_Off", "Off" }, { "Status_Running", "On" },
            { "Settings_Title", "Ajustes" }, { "Profile_Title", "Perfil" },
            { "Profile_Tip", "Define a fragmentação. Modo 5 balanceado." },
            { "Dns_Title", "DNS Seguro" }, { "Dns_Tip", "Evita manipulação de DNS por provedores." },
            { "Advanced_Title", "Filtros" }, { "Quic_Label", "Sem QUIC" }, { "Quic_Tip", "Força sites a usarem TCP." },
            { "Reverse_Label", "Reserva de pacotes" }, { "Reverse_Tip", "Ordem alterada para HTTPS." },
            { "Manual_Btn", "Manual" }, { "Reset_Btn", "Reset" }, { "Apply_Btn", "Aplicar" },
            { "Ask_Exit", "O que fazer?" }, { "Exit_Exit", "Sair" }, { "Exit_Hide", "Ocultar" }, { "Exit_Cancel", "Cancelar" },
            { "Toast_Applied", "✓ Salvo!" }, { "Language_Title", "Idiomas" },
            { "Blur_Label", "Desfoque (Blur)" }, { "Boot_Label", "Iniciar com boot" }, { "AutoStart_Label", "Auto-Início" },
            { "Unsaved_Msg", "Alterações não salvas!" }, { "Discard_Btn", "Descartar" },
            { "About_Title", "Sobre" }, { "Tray_Show", "Mostrar" }, { "Tray_Exit", "Sair" },
            { "Tray_Start", "Status: ON" }, { "Tray_Stop", "Status: OFF" },
            { "Reset_Msg", "Limpar tudo?" }, { "Reset_Confirm", "Reset" }
        }},
        { "pl", new Dictionary<string, string> {
            { "Status_Off", "Wył" }, { "Status_Running", "Wł" },
            { "Settings_Title", "Ustawienia" }, { "Profile_Title", "Profil" },
            { "Profile_Tip", "Tryb fragmentacji pakietów. Mod 5 jest optymalny." },
            { "Dns_Title", "Szyfrowany DNS" }, { "Dns_Tip", "Omija blokady DNS operatora." },
            { "Advanced_Title", "Filtry" }, { "Quic_Label", "Brak QUIC" }, { "Quic_Tip", "Wymusza użycie portu TCP." },
            { "Reverse_Label", "Odwrotna frag." }, { "Reverse_Tip", "Inna kolejność dla HTTPS." },
            { "Manual_Btn", "Tryb ręczny" }, { "Reset_Btn", "Reset" }, { "Apply_Btn", "Zapisz" },
            { "Ask_Exit", "Co zrobić?" }, { "Exit_Exit", "Zamknij" }, { "Exit_Hide", "Ukryj" }, { "Exit_Cancel", "Anuluj" },
            { "Toast_Applied", "✓ Zapisano!" }, { "Language_Title", "Języki" },
            { "Blur_Label", "Efekt rozmycia" }, { "Boot_Label", "Autostart System" }, { "AutoStart_Label", "Autostart Serwis" },
            { "Unsaved_Msg", "Niezapisane zmiany!" }, { "Discard_Btn", "Odrzuć" },
            { "About_Title", "O nas" }, { "Tray_Show", "Pokaż" }, { "Tray_Exit", "Wyjście" },
            { "Tray_Start", "Status: WŁ" }, { "Tray_Stop", "Status: WYŁ" },
            { "Reset_Msg", "Resetować ustawienia?" }, { "Reset_Confirm", "Tak" }
        }},
        { "az", new Dictionary<string, string> {
            { "Status_Off", "Dayandırıldı" }, { "Status_Running", "İşləyir" },
            { "Settings_Title", "Ayarlar" }, { "Profile_Title", "Profil" },
            { "Profile_Tip", "Paket parçalanmasını təyin edir. Rejim 5 daha stabildir." },
            { "Dns_Title", "Şifrəli DNS" }, { "Dns_Tip", "DNS manipulyasiyalarını keçir." },
            { "Advanced_Title", "Filtrlər" }, { "Quic_Label", "QUIC-i Bağla" }, { "Quic_Tip", "TCP istifadəsinə məcbur edir." },
            { "Reverse_Label", "Tərs parçalanma" }, { "Reverse_Tip", "HTTPS üçün fərqli sıra." },
            { "Manual_Btn", "Manual Menu" }, { "Reset_Btn", "Sıfırla" }, { "Apply_Btn", "Tətbiq et" },
            { "Ask_Exit", "Nə etməli?" }, { "Exit_Exit", "Çıxış" }, { "Exit_Hide", "Gizlə" }, { "Exit_Cancel", "Ləğv et" },
            { "Toast_Applied", "✓ Uğurla tətbiq edildi!" }, { "Language_Title", "Dillər" },
            { "Blur_Label", "Buzlu Şüşə Efekti" }, { "Boot_Label", "Açılışda başlat" }, { "AutoStart_Label", "Avto-başlatma" },
            { "Unsaved_Msg", "Yadda saxlanılmayanlar var!" }, { "Discard_Btn", "Ləğv et" },
            { "About_Title", "Haqqında" }, { "Tray_Show", "Göstər" }, { "Tray_Exit", "Bağla" },
            { "Tray_Start", "Vəziyyət: AÇIQ" }, { "Tray_Stop", "Vəziyyət: BAĞLI" },
            { "Reset_Msg", "Ayarlar sıfırlansın?" }, { "Reset_Confirm", "Sıfırla" }
        }},
        { "vi", new Dictionary<string, string> {
            { "Status_Off", "Đã Tắt" }, { "Status_Running", "Đang Chạy" },
            { "Settings_Title", "Cài Đặt" }, { "Profile_Title", "Cấu Hình" },
            { "Profile_Tip", "Xác định phân mảnh gói tin. Chế độ 5 là ổn định nhất." },
            { "Dns_Title", "DNS Mã Hóa" }, { "Dns_Tip", "Vượt qua thao túng DNS của nhà mạng." },
            { "Advanced_Title", "Bộ Lọc" }, { "Quic_Label", "Tắt QUIC" }, { "Quic_Tip", "Buộc các trang web sử dụng TCP." },
            { "Reverse_Label", "Phân Mảnh Ngược" }, { "Reverse_Tip", "Sử dụng thứ tự gói khác cho HTTPS." },
            { "Manual_Btn", "Thủ Công" }, { "Reset_Btn", "Đặt Lại" }, { "Apply_Btn", "Áp Dụng" },
            { "Ask_Exit", "Bạn muốn làm gì?" }, { "Exit_Exit", "Thoát" }, { "Exit_Hide", "Ẩn" }, { "Exit_Cancel", "Hủy" },
            { "Toast_Applied", "✓ Đã lưu cài đặt!" }, { "Language_Title", "Ngôn Ngữ" },
            { "Blur_Label", "Hiệu Ứng Làm Mờ" }, { "Boot_Label", "Khởi Động Cùng Hệ Thống" }, { "AutoStart_Label", "Tự Động Chạy Dịch Vụ" },
            { "Unsaved_Msg", "Có thay đổi chưa lưu!" }, { "Discard_Btn", "Bỏ qua" },
            { "About_Title", "Thông tin" }, { "Tray_Show", "Hiện" }, { "Tray_Exit", "Thoát" },
            { "Tray_Start", "Chế độ: BẬT" }, { "Tray_Stop", "Chế độ: TẮT" },
            { "Reset_Msg", "Đặt lại toàn bộ cài đặt?" }, { "Reset_Confirm", "Đặt lại" }
        }},
        { "th", new Dictionary<string, string> {
            { "Status_Off", "ปิด" }, { "Status_Running", "กำลังทำงาน" },
            { "Settings_Title", "การตั้งค่า" }, { "Profile_Title", "โปรไฟล์" },
            { "Profile_Tip", "กำหนดการแบ่งส่วนแพ็กเก็ต โหมด 5 มีความสมดุลที่สุด" },
            { "Dns_Title", "DNS ที่เข้ารหัส" }, { "Dns_Tip", "ข้ามการจัดการ DNS โดย ISP" },
            { "Advanced_Title", "ตัวกรอง" }, { "Quic_Label", "ปิดใช้งาน QUIC" }, { "Quic_Tip", "บังคับให้ใช้ TCP แทน UDP" },
            { "Reverse_Label", "การแบ่งส่วนย้อนกลับ" }, { "Reverse_Tip", "ใช้ลำดับแพ็กเก็ตที่แตกต่างกันสำหรับ HTTPS" },
            { "Manual_Btn", "กำหนดเอง" }, { "Reset_Btn", "รีเซ็ต" }, { "Apply_Btn", "บันทึก" },
            { "Ask_Exit", "คุณต้องการทำอะไร?" }, { "Exit_Exit", "ออก" }, { "Exit_Hide", "ซ่อน" }, { "Exit_Cancel", "ยกเลิก" },
            { "Toast_Applied", "✓ บันทึกสำเร็จ!" }, { "Language_Title", "ภาษา" },
            { "Blur_Label", "เอฟเฟกต์เบลอ" }, { "Boot_Label", "เริ่มพร้อมระบบ" }, { "AutoStart_Label", "เริ่มบริการอัตโนมัติ" },
            { "Unsaved_Msg", "มีการเปลี่ยนแปลงที่ยังไม่ได้บันทึก!" }, { "Discard_Btn", "ละทิ้ง" },
            { "About_Title", "เกี่ยวกับ" }, { "Tray_Show", "แสดง" }, { "Tray_Exit", "ออก" },
            { "Tray_Start", "โหมด: เปิด" }, { "Tray_Stop", "โหมด: ปิด" },
            { "Reset_Msg", "รีเซ็ตการตั้งค่าทั้งหมดหรือไม่?" }, { "Reset_Confirm", "รีเซ็ต" }
        }},
        { "id", new Dictionary<string, string> {
            { "Status_Off", "Mati" }, { "Status_Running", "Berjalan" },
            { "Settings_Title", "Pengaturan" }, { "Profile_Title", "Profil" },
            { "Profile_Tip", "Menentukan fragmentasi paket. Mode 5 seimbang." },
            { "Dns_Title", "DNS Terenskripsi" }, { "Dns_Tip", "Melewati manipulasi DNS ISP." },
            { "Advanced_Title", "Filter" }, { "Quic_Label", "Nonaktifkan QUIC" }, { "Quic_Tip", "Memaksa situs menggunakan TCP." },
            { "Reverse_Label", "Frag. Terbalik" }, { "Reverse_Tip", "Urutan paket berbeda untuk HTTPS." },
            { "Manual_Btn", "Manual" }, { "Reset_Btn", "Reset" }, { "Apply_Btn", "Terapkan" },
            { "Ask_Exit", "Mau ngapain?" }, { "Exit_Exit", "Keluar" }, { "Exit_Hide", "Sembunyikan" }, { "Exit_Cancel", "Batal" },
            { "Toast_Applied", "✓ Berhasil!" }, { "Language_Title", "Bahasa" },
            { "Blur_Label", "Efek Blur" }, { "Boot_Label", "Mulai saat bitt" }, { "AutoStart_Label", "Auto-start layanan" },
            { "Unsaved_Msg", "Perubahan belum di simpan!" }, { "Discard_Btn", "Buang" },
            { "About_Title", "Tentang" }, { "Tray_Show", "Tampilkan" }, { "Tray_Exit", "Keluar" },
            { "Tray_Start", "Status: ON" }, { "Tray_Stop", "Status: OFF" },
            { "Reset_Msg", "Reset semua pengaturan?" }, { "Reset_Confirm", "Reset" }
        }},
        { "ko", new Dictionary<string, string> {
            { "Status_Off", "꺼짐" }, { "Status_Running", "실행 중" },
            { "Settings_Title", "설정" }, { "Profile_Title", "전원 프로필" },
            { "Profile_Tip", "패킷 파편화 방식 결정. 모드 5가 가장 적절함." },
            { "Dns_Title", "암호화된 DNS" }, { "Dns_Tip", "통신사 DNS 변조 우회." },
            { "Advanced_Title", "필터" }, { "Quic_Label", "QUIC 비활성화" }, { "Quic_Tip", "TCP 사용을 강제합니다." },
            { "Reverse_Label", "역방향 파편화" }, { "Reverse_Tip", "HTTPS에 다른 패킷 순서 사용." },
            { "Manual_Btn", "수동 메뉴" }, { "Reset_Btn", "초기화" }, { "Apply_Btn", "적용" },
             { "Ask_Exit", "무엇을 하시겠습니까?" }, { "Exit_Exit", "전체 종료" }, { "Exit_Hide", "숨기기" }, { "Exit_Cancel", "취소" },
            { "Toast_Applied", "✓ 설정 완료!" }, { "Language_Title", "언어 설정" },
            { "Blur_Label", "블러 효과" }, { "Boot_Label", "부팅 시 시작" }, { "AutoStart_Label", "자동 시작" },
            { "Unsaved_Msg", "저장되지 않은 변경사항!" }, { "Discard_Btn", "무시하고 종료" },
            { "About_Title", "정보" }, { "Tray_Show", "보이기" }, { "Tray_Exit", "종료" },
            { "Tray_Start", "상태: 켬" }, { "Tray_Stop", "상태: 끔" },
            { "Reset_Msg", "초기화할까요?" }, { "Reset_Confirm", "확인" }
        }},
        { "ja", new Dictionary<string, string> {
            { "Status_Off", "停止" }, { "Status_Running", "実行中" },
            { "Settings_Title", "設定" }, { "Profile_Title", "プロファイル" },
            { "Profile_Tip", "断片化の強さを設定。モード5が推奨。" },
            { "Dns_Title", "暗号化 DNS" }, { "Dns_Tip", "プロバイダのDNS制限を回避。" },
            { "Advanced_Title", "フィルタ" }, { "Quic_Label", "QUIC を無効化" }, { "Quic_Tip", "TCP接続を強制します。" },
            { "Reverse_Label", "逆断片化" }, { "Reverse_Tip", "HTTPS用に順序を変更。" },
            { "Manual_Btn", "手動" }, { "Reset_Btn", "リセット" }, { "Apply_Btn", "適用" },
            { "Ask_Exit", "どの操作を行いますか？" }, { "Exit_Exit", "終了" }, { "Exit_Hide", "隠す" }, { "Exit_Cancel", "キャンセル" },
            { "Toast_Applied", "✓ 保存しました!" }, { "Language_Title", "言語設定" },
            { "Blur_Label", "ぼかしエフェクト" }, { "Boot_Label", "自動起動" }, { "AutoStart_Label", "サービス自動開始" },
            { "Unsaved_Msg", "未保存の変更があります!" }, { "Discard_Btn", "戻る" },
            { "About_Title", "バージョン情報" }, { "Tray_Show", "開く" }, { "Tray_Exit", "閉じる" },
            { "Tray_Start", "動作: オン" }, { "Tray_Stop", "動作: オフ" },
            { "Reset_Msg", "初期化しますか？" }, { "Reset_Confirm", "はい" }
        }},
        { "nl", new Dictionary<string, string> {
            { "Status_Off", "Uit" }, { "Status_Running", "Aan het draaien" },
            { "Settings_Title", "Instellingen" }, { "Profile_Title", "Profiel" }, { "Profile_Tip", "Bepaal fragmentatie. Mode 5 is gebalanceerd." },
            { "Dns_Title", "Versleutelde DNS" }, { "Dns_Tip", "Omzeil ISP DNS-manipulatie." },
            { "Advanced_Title", "Filters" }, { "Quic_Label", "QUIC uitschakelen" }, { "Quic_Tip", "Dwingt TCP af." },
            { "Reverse_Label", "Omgekeerde frag." }, { "Reverse_Tip", "Andere volgorde voor HTTPS." },
            { "Manual_Btn", "Handmatig" }, { "Reset_Btn", "Reset" }, { "Apply_Btn", "Toepassen" },
            { "Ask_Exit", "Wat wilt u doen?" }, { "Exit_Exit", "Afsluiten" }, { "Exit_Hide", "Verbergen" }, { "Exit_Cancel", "Annuleren" },
            { "Toast_Applied", "✓ Opgeslagen!" }, { "Language_Title", "Talen" },
            { "Blur_Label", "Vervaging (Blur)" }, { "Boot_Label", "Starten met systeem" }, { "AutoStart_Label", "Auto-start service" },
            { "Unsaved_Msg", "Niet opgeslagen wijzigingen!" }, { "Discard_Btn", "Weggooien" },
            { "About_Title", "Over" }, { "Tray_Show", "Tonen" }, { "Tray_Exit", "Sluiten" },
            { "Tray_Start", "Status: AAN" }, { "Tray_Stop", "Status: UIT" },
            { "Reset_Msg", "Alles herstellen?" }, { "Reset_Confirm", "Confirm" }
        }},
        { "sv", new Dictionary<string, string> {
            { "Status_Off", "Av" }, { "Status_Running", "Körs" },
            { "Settings_Title", "Inställningar" }, { "Profile_Title", "Profil" }, { "Profile_Tip", "Fragmenteringsläge. Läge 5 är balanserat." },
            { "Dns_Title", "Krypterad DNS" }, { "Dns_Tip", "Kringgår ISP:s DNS-manipulation." },
            { "Advanced_Title", "Filter" }, { "Quic_Label", "Inaktivera QUIC" }, { "Quic_Tip", "Tvingar TCP." },
            { "Reverse_Label", "Omvänd frag." }, { "Reverse_Tip", "Annan paketordning för HTTPS." },
            { "Manual_Btn", "Manuellt" }, { "Reset_Btn", "Återställ" }, { "Apply_Btn", "Spara" },
            { "Ask_Exit", "Vad göra?" }, { "Exit_Exit", "Avsluta" }, { "Exit_Hide", "Dölj" }, { "Exit_Cancel", "Avbryt" },
            { "Toast_Applied", "✓ Sparat!" }, { "Language_Title", "Språk" },
            { "Blur_Label", "Glas-effekt" }, { "Boot_Label", "Autostart" }, { "AutoStart_Label", "Auto-start tjänst" },
            { "Unsaved_Msg", "Osparade ändringar!" }, { "Discard_Btn", "Kasta" },
            { "About_Title", "Om" }, { "Tray_Show", "Visa" }, { "Tray_Exit", "Avsluta" },
            { "Tray_Start", "Läge: PÅ" }, { "Tray_Stop", "Läge: AV" },
            { "Reset_Msg", "Återställ allt?" }, { "Reset_Confirm", "Svar" }
        }},
        { "no", new Dictionary<string, string> {
            { "Status_Off", "Av" }, { "Status_Running", "Kjører" },
            { "Settings_Title", "Innstillinger" }, { "Profile_Title", "Profil" }, { "Profile_Tip", "Bestemmer fragmentering. Modus 5 er best." },
            { "Dns_Title", "Kryptert DNS" }, { "Dns_Tip", "Omgår lokal DNS-manipulasjon." },
            { "Advanced_Title", "Filtre" }, { "Quic_Label", "Deaktiver QUIC" }, { "Quic_Tip", "Tvinger TCP." },
            { "Reverse_Label", "Revers frag." }, { "Reverse_Tip", "Annen rekkefølge for HTTPS." },
            { "Manual_Btn", "Manuelt" }, { "Reset_Btn", "Nullstill" }, { "Apply_Btn", "Bruk" },
            { "Ask_Exit", "Hva vil du gjøre?" }, { "Exit_Exit", "Avslutt" }, { "Exit_Hide", "Skjul" }, { "Exit_Cancel", "Avbryt" },
            { "Toast_Applied", "✓ Brukt!" }, { "Language_Title", "Språk" },
            { "Blur_Label", "Blur-effekt" }, { "Boot_Label", "Systemstart" }, { "AutoStart_Label", "Tjenestestart" },
            { "Unsaved_Msg", "Ulagrede endringer!" }, { "Discard_Btn", "Forkast" },
            { "About_Title", "Om" }, { "Tray_Show", "Vis" }, { "Tray_Exit", "Avslutt" },
            { "Tray_Start", "Status: PÅ" }, { "Tray_Stop", "Status: AV" },
            { "Reset_Msg", "Nullstill alt?" }, { "Reset_Confirm", "Ja" }
        }},
        { "da", new Dictionary<string, string> {
            { "Status_Off", "Fra" }, { "Status_Running", "Kører" },
            { "Settings_Title", "Indstillinger" }, { "Profile_Title", "Profil" }, { "Profile_Tip", "Bestemmer fragmentering. Modus 5 er bedst." },
            { "Dns_Title", "Kryptered DNS" }, { "Dns_Tip", "Omgår ISP DNS-blokering." },
            { "Advanced_Title", "Filtre" }, { "Quic_Label", "Deaktiver QUIC" }, { "Quic_Tip", "Tvinger TCP." },
            { "Reverse_Label", "Omvendt frag." }, { "Reverse_Tip", "Anden pakkeorden for HTTPS." },
            { "Manual_Btn", "Manuel" }, { "Reset_Btn", "Nulstil" }, { "Apply_Btn", "Anvend" },
            { "Ask_Exit", "Hvad nu?" }, { "Exit_Exit", "Afslut" }, { "Exit_Hide", "Skjul" }, { "Exit_Cancel", "Fortryd" },
            { "Toast_Applied", "✓ Gemt!" }, { "Language_Title", "Sprog" },
            { "Blur_Label", "Sløringseffekt" }, { "Boot_Label", "Autostart System" }, { "AutoStart_Label", "Autostart Service" },
            { "Unsaved_Msg", "Ugemte ændringer!" }, { "Discard_Btn", "Kassér" },
            { "About_Title", "Om" }, { "Tray_Show", "Vis" }, { "Tray_Exit", "Afslut" },
            { "Tray_Start", "Status: TIL" }, { "Tray_Stop", "Status: FRA" },
            { "Reset_Msg", "Nulstil alt?" }, { "Reset_Confirm", "Svar" }
        }},
        { "fi", new Dictionary<string, string> {
            { "Status_Off", "Pois" }, { "Status_Running", "Käynnissä" },
            { "Settings_Title", "Asetukset" }, { "Profile_Title", "Profiili" }, { "Profile_Tip", "Fragmentointi. Tila 5 on tasapainoinen." },
            { "Dns_Title", "Salattu DNS" }, { "Dns_Tip", "Ohittaa tarjoajan DNS-rajoitukset." },
            { "Advanced_Title", "Suodattimet" }, { "Quic_Label", "Poista QUIC" }, { "Quic_Tip", "Pakottaa TCP:n." },
            { "Reverse_Label", "Käänteinen frag." }, { "Reverse_Tip", "Eri pakettijärjestys HTTPS:lle." },
            { "Manual_Btn", "Manuaalinen" }, { "Reset_Btn", "Nollaa" }, { "Apply_Btn", "Käytä" },
            { "Ask_Exit", "Mitä tehdään?" }, { "Exit_Exit", "Lopeta" }, { "Exit_Hide", "Piilota" }, { "Exit_Cancel", "Peruuta" },
            { "Toast_Applied", "✓ Tallennettu!" }, { "Language_Title", "Kielet" },
            { "Blur_Label", "Sumuefekti" }, { "Boot_Label", "Autostart" }, { "AutoStart_Label", "Palvelun autostart" },
            { "Unsaved_Msg", "Tallentamattomia muutoksia!" }, { "Discard_Btn", "Hylkää" },
            { "About_Title", "Tietoa" }, { "Tray_Show", "Näytä" }, { "Tray_Exit", "Lopeta" },
            { "Tray_Start", "Tila: PÄÄLLÄ" }, { "Tray_Stop", "Tila: POIS" },
            { "Reset_Msg", "Nollaa kaikki?" }, { "Reset_Confirm", "Kyllä" }
        }},
        { "sr", new Dictionary<string, string> {
            { "Status_Off", "Isključeno" }, { "Status_Running", "Radi" },
            { "Settings_Title", "Postavke" }, { "Profile_Title", "Profil" }, { "Profile_Tip", "Određuje fragmentaciju. Režim 5 je balansiran." },
            { "Dns_Title", "Enkriptovan DNS" }, { "Dns_Tip", "Zaobilazi ISP manipulacije." },
            { "Advanced_Title", "Filteri" }, { "Quic_Label", "Isključi QUIC" }, { "Quic_Tip", "Primorava sajtove na TCP." },
            { "Reverse_Label", "Obrnuti frag." }, { "Reverse_Tip", "Drugi redosled paketa za HTTPS." },
            { "Manual_Btn", "Ručno" }, { "Reset_Btn", "Resetuj" }, { "Apply_Btn", "Primeni" },
            { "Ask_Exit", "Šta želite?" }, { "Exit_Exit", "Izađi" }, { "Exit_Hide", "Sakrij" }, { "Exit_Cancel", "Otkaži" },
            { "Toast_Applied", "✓ Sačuvano!" }, { "Language_Title", "Jezici" },
            { "Blur_Label", "Blur efekat" }, { "Boot_Label", "Start sa sistemom" }, { "AutoStart_Label", "Auto-start usluge" },
            { "Unsaved_Msg", "Nesačuvane promene!" }, { "Discard_Btn", "Odbaci" },
            { "About_Title", "O programu" }, { "Tray_Show", "Prikaži" }, { "Tray_Exit", "Izađi" },
            { "Tray_Start", "Status: UKLJ" }, { "Tray_Stop", "Status: ISKLJ" },
            { "Reset_Msg", "Resetuj sve?" }, { "Reset_Confirm", "Da" }
        }},
        { "hr", new Dictionary<string, string> {
            { "Status_Off", "Isključeno" }, { "Status_Running", "Radi" },
            { "Settings_Title", "Postavke" }, { "Profile_Title", "Profil" }, { "Profile_Tip", "Određuje fragmentaciju. Način 5 je uravnotežen." },
            { "Dns_Title", "Enkriptiran DNS" }, { "Dns_Tip", "Zaobilazi DNS manipulacije ISP-a." },
            { "Advanced_Title", "Filteri" }, { "Quic_Label", "Isključi QUIC" }, { "Quic_Tip", "Prisiljava stranice na TCP." },
            { "Reverse_Label", "Obrnuti frag." }, { "Reverse_Tip", "Drugačiji redoslijed paketa za HTTPS." },
            { "Manual_Btn", "Ručno" }, { "Reset_Btn", "Resetiraj" }, { "Apply_Btn", "Primijeni" },
            { "Ask_Exit", "Što želite?" }, { "Exit_Exit", "Izađi" }, { "Exit_Hide", "Sakrij" }, { "Exit_Cancel", "Odustani" },
            { "Toast_Applied", "✓ Spremljeno!" }, { "Language_Title", "Jezici" },
            { "Blur_Label", "Blur efekt" }, { "Boot_Label", "Start sa sustavom" }, { "AutoStart_Label", "Auto-start usluge" },
            { "Unsaved_Msg", "Nespremljene promjene!" }, { "Discard_Btn", "Odbaci" },
            { "About_Title", "O programu" }, { "Tray_Show", "Prikaži" }, { "Tray_Exit", "Izađi" },
            { "Tray_Start", "Status: UKLJ" }, { "Tray_Stop", "Status: ISKLJ" },
            { "Reset_Msg", "Resetiraj sve?" }, { "Reset_Confirm", "Da" }
        }},
        { "sk", new Dictionary<string, string> {
            { "Status_Off", "Vypnuté" }, { "Status_Running", "Beží" },
            { "Settings_Title", "Nastavenia" }, { "Profile_Title", "Profil" }, { "Profile_Tip", "Určuje fragmentáciu. Režim 5 je vyvážený." },
            { "Dns_Title", "Šifrované DNS" }, { "Dns_Tip", "Obchádza manipuláciu DNS od ISP." },
            { "Advanced_Title", "Filtre" }, { "Quic_Label", "Vypnúť QUIC" }, { "Quic_Tip", "Vynúti použitie TCP." },
            { "Reverse_Label", "Reverzný frag." }, { "Reverse_Tip", "Iné poradie paketov pre HTTPS." },
            { "Manual_Btn", "Ručne" }, { "Reset_Btn", "Resetovať" }, { "Apply_Btn", "Použiť" },
            { "Ask_Exit", "Čo ďalej?" }, { "Exit_Exit", "Ukončiť" }, { "Exit_Hide", "Skryť" }, { "Exit_Cancel", "Zrušiť" },
            { "Toast_Applied", "✓ Uložené!" }, { "Language_Title", "Jazyky" },
            { "Blur_Label", "Efekt rozostrenia" }, { "Boot_Label", "Spúšťať po bootu" }, { "AutoStart_Label", "Auto-štart služby" },
            { "Unsaved_Msg", "Neuložené zmeny!" }, { "Discard_Btn", "Zahodiť" },
            { "About_Title", "O programe" }, { "Tray_Show", "Ukázať" }, { "Tray_Exit", "Koniec" },
            { "Tray_Start", "Stav: ZAP" }, { "Tray_Stop", "Stav: VYP" },
            { "Reset_Msg", "Resetovať všetko?" }, { "Reset_Confirm", "Áno" }
        }},
        { "ro", new Dictionary<string, string> {
            { "Status_Off", "Oprit" }, { "Status_Running", "Activ" },
            { "Settings_Title", "Setări" }, { "Profile_Title", "Profil" }, { "Profile_Tip", "Fragmentarea pachetelor. Modul 5 este echilibrat." },
            { "Dns_Title", "DNS Criptat" }, { "Dns_Tip", "Ocolește manipularea DNS a ISP-ului." },
            { "Advanced_Title", "Filtre" }, { "Quic_Label", "Dezactivează QUIC" }, { "Quic_Tip", "Forțează TCP." },
            { "Reverse_Label", "Frag. Inversă" }, { "Reverse_Tip", "Ordine diferită pentru HTTPS." },
            { "Manual_Btn", "Manual" }, { "Reset_Btn", "Resetare" }, { "Apply_Btn", "Aplică" },
            { "Ask_Exit", "Ce doriți?" }, { "Exit_Exit", "Ieşire" }, { "Exit_Hide", "Ascunde" }, { "Exit_Cancel", "Anulează" },
            { "Toast_Applied", "✓ Salvat!" }, { "Language_Title", "Limbi" },
            { "Blur_Label", "Efect de estompare" }, { "Boot_Label", "Lansare la boot" }, { "AutoStart_Label", "Auto-pornire" },
            { "Unsaved_Msg", "Modificări nesalvate!" }, { "Discard_Btn", "Renunță" },
            { "About_Title", "Despre" }, { "Tray_Show", "Afișează" }, { "Tray_Exit", "Ieşire" },
            { "Tray_Start", "Mod: ACTIV" }, { "Tray_Stop", "Mod: OPRIT" },
            { "Reset_Msg", "Resetați totul?" }, { "Reset_Confirm", "Sî" }
        }},
        { "hu", new Dictionary<string, string> {
            { "Status_Off", "Kikapcsolva" }, { "Status_Running", "Fut" },
            { "Settings_Title", "Beállítások" }, { "Profile_Title", "Profil" }, { "Profile_Tip", "Fragmentáció típus. Az 5. mód kiegyensúlyozott." },
            { "Dns_Title", "Titkosított DNS" }, { "Dns_Tip", "Kikerüli az ISP-s DNS blokkolást." },
            { "Advanced_Title", "Szűrők" }, { "Quic_Label", "QUIC Tiltása" }, { "Quic_Tip", "Kényszerített TCP használat." },
            { "Reverse_Label", "Fordított frag." }, { "Reverse_Tip", "Más csomagsorrend HTTPS-hez." },
            { "Manual_Btn", "Manuális" }, { "Reset_Btn", "Visszaállítás" }, { "Apply_Btn", "Mentés" },
            { "Ask_Exit", "Kilép?" }, { "Exit_Exit", "Bezárás" }, { "Exit_Hide", "Elrejtés" }, { "Exit_Cancel", "Mégse" },
            { "Toast_Applied", "✓ Alkalmazva!" }, { "Language_Title", "Nyelvek" },
            { "Blur_Label", "Elmosódás effekt" }, { "Boot_Label", "Indítás a rendszerrel" }, { "AutoStart_Label", "Auto-indítás" },
            { "Unsaved_Msg", "Nem mentett adatok!" }, { "Discard_Btn", "Elvetés" },
            { "About_Title", "Névjegy" }, { "Tray_Show", "Mutat" }, { "Tray_Exit", "Kilépés" },
            { "Tray_Start", "Állapot: BE" }, { "Tray_Stop", "Állapot: KI" },
            { "Reset_Msg", "Mindent töröl?" }, { "Reset_Confirm", "Igen" }
        }},
        { "cs", new Dictionary<string, string> {
            { "Status_Off", "Vypnuto" }, { "Status_Running", "Spuštěno" },
            { "Settings_Title", "Nastavení" }, { "Profile_Title", "Profil" }, { "Profile_Tip", "Určuje fragmentaci. Režim 5 je stabilní." },
            { "Dns_Title", "Šifrované DNS" }, { "Dns_Tip", "Obchází manipulaci DNS od ISP." },
            { "Advanced_Title", "Filtry" }, { "Quic_Label", "Vypnout QUIC" }, { "Quic_Tip", "Vynutí použití TCP." },
            { "Reverse_Label", "Reverzní frag." }, { "Reverse_Tip", "Jiné pořadí paketů pro HTTPS." },
            { "Manual_Btn", "Ručně" }, { "Reset_Btn", "Resetovat" }, { "Apply_Btn", "Použít" },
            { "Ask_Exit", "Co dál?" }, { "Exit_Exit", "Ukončit" }, { "Exit_Hide", "Skrýt" }, { "Exit_Cancel", "Storno" },
            { "Toast_Applied", "✓ Uloženo!" }, { "Language_Title", "Jazyky" },
            { "Blur_Label", "Efekt rozostření" }, { "Boot_Label", "Spouštět po bootu" }, { "AutoStart_Label", "Auto-start služby" },
            { "Unsaved_Msg", "Neuložené změny!" }, { "Discard_Btn", "Zahodit" },
            { "About_Title", "O programu" }, { "Tray_Show", "Ukázat" }, { "Tray_Exit", "Konec" },
            { "Tray_Start", "Stav: ZAP" }, { "Tray_Stop", "Stav: VYP" },
            { "Reset_Msg", "Resetovat vše?" }, { "Reset_Confirm", "Reset" }
        }},
        { "el", new Dictionary<string, string> {
            { "Status_Off", "Ανενεργό" }, { "Status_Running", "Ενεργό" },
            { "Settings_Title", "Ρυθμίσεις" }, { "Profile_Title", "Προφίλ" }, { "Profile_Tip", "Καθορισμός κατακερματισμού. Η λειτουργία 5 είναι ισορροπημένη." },
            { "Dns_Title", "Κρυπτογραφημένο DNS" }, { "Dns_Tip", "Παράκαμψη χειραγώγησης DNS παρόχου." },
            { "Advanced_Title", "Φίλτρα" }, { "Quic_Label", "Απενεργοποίηση QUIC" }, { "Quic_Tip", "Επιβολή χρήσης TCP." },
            { "Reverse_Label", "Αντίστροφο Frag" }, { "Reverse_Tip", "Διαφορετική σειρά πακέτων για HTTPS." },
            { "Manual_Btn", "Χειροκίνητα" }, { "Reset_Btn", "Επαναφορά" }, { "Apply_Btn", "Εφαρμογή" },
            { "Ask_Exit", "Τι θέλετε να κάνετε;" }, { "Exit_Exit", "Έξοδος" }, { "Exit_Hide", "Απόκρυψη" }, { "Exit_Cancel", "Άκυρο" },
            { "Toast_Applied", "✓ Αποτυχία!" }, { "Language_Title", "Γλώσσες" },
            { "Blur_Label", "Εφέ Θολώματος" }, { "Boot_Label", "Εκκίνηση συστήματος" }, { "AutoStart_Label", "Αυτόματη εκκίνηση" },
            { "Unsaved_Msg", "Μη αποθηκευμένες αλλαγές!" }, { "Discard_Btn", "Απόρριψη" },
            { "About_Title", "Σχετικά" }, { "Tray_Show", "Εμφάνιση" }, { "Tray_Exit", "Έξοδος" },
            { "Tray_Start", "Λειτουργία: ΝΑΙ" }, { "Tray_Stop", "Λειτουργία: ΟΧΙ" },
            { "Reset_Msg", "Επαναφορά όλων;" }, { "Reset_Confirm", "Ναι" }
        }},
        { "bg", new Dictionary<string, string> {
            { "Status_Off", "Изключено" }, { "Status_Running", "Работи" },
            { "Settings_Title", "Настройки" }, { "Profile_Title", "Профил" }, { "Profile_Tip", "Определя фрагментацията. Режим 5 е балансиран." },
            { "Dns_Title", "Криптиран DNS" }, { "Dns_Tip", "Заобикаля манипулациите на доставчика." },
            { "Advanced_Title", "Филтри" }, { "Quic_Label", "Изключи QUIC" }, { "Quic_Tip", "Принуждава сайтовете към TCP." },
            { "Reverse_Label", "Обратна фрагм." }, { "Reverse_Tip", "Друг пакетен ред за HTTPS." },
            { "Manual_Btn", "Ръчно" }, { "Reset_Btn", "Нулирай" }, { "Apply_Btn", "Приложи" },
            { "Ask_Exit", "Какво ще правим?" }, { "Exit_Exit", "Изход" }, { "Exit_Hide", "Скрий" }, { "Exit_Cancel", "Отказ" },
            { "Toast_Applied", "✓ Запазено!" }, { "Language_Title", "Езици" },
            { "Blur_Label", "Размиване" }, { "Boot_Label", "Старт със системата" }, { "AutoStart_Label", "Авто-старт услуга" },
            { "Unsaved_Msg", "Незапазени промени!" }, { "Discard_Btn", "Отхвърли" },
            { "About_Title", "За нас" }, { "Tray_Show", "Покажи" }, { "Tray_Exit", "Изход" },
            { "Tray_Start", "Статус: ВКЛ" }, { "Tray_Stop", "Статус: ИЗКЛ" },
            { "Reset_Msg", "Нулиране на настройки?" }, { "Reset_Confirm", "Да" }
        }},
        { "he", new Dictionary<string, string> {
            { "Status_Off", "כבוי" }, { "Status_Running", "פועל" },
            { "Settings_Title", "הגדרות" }, { "Profile_Title", "פרופיל" }, { "Profile_Tip", "קובע את הפיצול. מצב 5 הוא המאוזן ביותר." },
            { "Dns_Title", "DNS מוצפן" }, { "Dns_Tip", "עוקף מניפולציות DNS של ספק התשתית." },
            { "Advanced_Title", "מסננים" }, { "Quic_Label", "ביטול QUIC" }, { "Quic_Tip", "מאלץ אתרים להשתמש ב-TCP." },
            { "Reverse_Label", "פיצול הפוך" }, { "Reverse_Tip", "סדר חבילות שונה עבור HTTPS." },
            { "Manual_Btn", "ידני" }, { "Reset_Btn", "איפוס" }, { "Apply_Btn", "החל" },
            { "Ask_Exit", "מה ברצונך לעשות?" }, { "Exit_Exit", "יציאה" }, { "Exit_Hide", "הסתר" }, { "Exit_Cancel", "ביטול" },
            { "Toast_Applied", "✓ נשמר!" }, { "Language_Title", "שפות" },
            { "Blur_Label", "אפקט טשטוש" }, { "Boot_Label", "הפעלה עם המערכת" }, { "AutoStart_Label", "הפעלה אוטומטית" },
            { "Unsaved_Msg", "שינויים לא שמורים!" }, { "Discard_Btn", "התעלם" },
            { "About_Title", "אודות" }, { "Tray_Show", "הצג" }, { "Tray_Exit", "יציאה" },
            { "Tray_Start", "מצב: פועל" }, { "Tray_Stop", "מצב: כבוי" },
            { "Reset_Msg", "לאפס את הכל?" }, { "Reset_Confirm", "איפוס" }
        }},
        { "fa", new Dictionary<string, string> {
            { "Status_Off", "خاموش" }, { "Status_Running", "در حال اجرا" },
            { "Settings_Title", "تنظیمات" }, { "Profile_Title", "پروفایل" }, { "Profile_Tip", "تعیین نحوه تکه‌تکه کردن بسته‌ها. حالت ۵ متوازن است." },
            { "Dns_Title", "دی‌ان‌اس رمزنگاری شده" }, { "Dns_Tip", "دور زدن دستکاری‌های DNS اپراتور." },
            { "Advanced_Title", "فیلترها" }, { "Quic_Label", "غیرفعال کردن QUIC" }, { "Quic_Tip", "اجبار به استفاده از پروتکل TCP." },
            { "Reverse_Label", "تکه بستن معکوس" }, { "Reverse_Tip", "ترتیب متفاوت بسته برای HTTPS." },
            { "Manual_Btn", "دستی" }, { "Reset_Btn", "بازنشانی" }, { "Apply_Btn", "اعمال" },
            { "Ask_Exit", "چه کاری انجام شود؟" }, { "Exit_Exit", "خروج" }, { "Exit_Hide", "مخفی کردن" }, { "Exit_Cancel", "لغو" },
            { "Toast_Applied", "✓ اعمال شد!" }, { "Language_Title", "زبان‌ها" },
            { "Blur_Label", "افکت ماتی" }, { "Boot_Label", "شروع هنگام بوت" }, { "AutoStart_Label", "شروع خودکار سرویس" },
            { "Unsaved_Msg", "تغییرات ذخیره نشده!" }, { "Discard_Btn", "رها کردن" },
            { "About_Title", "درباره" }, { "Tray_Show", "نمایش" }, { "Tray_Exit", "خروج" },
            { "Tray_Start", "وضعیت: روشن" }, { "Tray_Stop", "وضعیت: خاموش" },
            { "Reset_Msg", "همه تنظیمات بازنشانی شوند؟" }, { "Reset_Confirm", "تأیید" }
        }},
        { "ms", new Dictionary<string, string> {
            { "Status_Off", "Mati" }, { "Status_Running", "Aktif" },
            { "Settings_Title", "Tetapan" }, { "Profile_Title", "Profil" }, { "Profile_Tip", "Menentukan fragmentasi paket. Mod 5 paling stabil." },
            { "Dns_Title", "DNS Berenkripsi" }, { "Dns_Tip", "Melepasi manipulasi DNS ISP." },
            { "Advanced_Title", "Penapis" }, { "Quic_Label", "Nyahaktif QUIC" }, { "Quic_Tip", "Memaksa penggunaan TCP." },
            { "Reverse_Label", "Frag. Terbalik" }, { "Reverse_Tip", "Urutan paket berbeza untuk HTTPS." },
            { "Manual_Btn", "Manual" }, { "Reset_Btn", "Set Semula" }, { "Apply_Btn", "Guna" },
            { "Ask_Exit", "Tindakan?" }, { "Exit_Exit", "Keluar" }, { "Exit_Hide", "Sembunyi" }, { "Exit_Cancel", "Batal" },
            { "Toast_Applied", "✓ Berjaya!" }, { "Language_Title", "Bahasa" },
            { "Blur_Label", "Kesan Blur" }, { "Boot_Label", "Mula semasa boot" }, { "AutoStart_Label", "Automula semula" },
            { "Unsaved_Msg", "Perubahan belum simpan!" }, { "Discard_Btn", "Buang" },
            { "About_Title", "Perihal" }, { "Tray_Show", "Tunjuk" }, { "Tray_Exit", "Keluar" },
            { "Tray_Start", "Status: HIDUP" }, { "Tray_Stop", "Status: MATI" },
            { "Reset_Msg", "Set semula semua?" }, { "Reset_Confirm", "Ya" }
        }},
        { "bn", new Dictionary<string, string> {
            { "Status_Off", "বন্ধ" }, { "Status_Running", "চলছে" },
            { "Settings_Title", "সেটিংস" }, { "Profile_Title", "প্রোফাইল" }, { "Profile_Tip", "প্যাকেট ফ্র্যাগমেন্টেশন নির্ধারণ করে। মোড ৫ সেরা।" },
            { "Dns_Title", "এনক্রিপ্টেড DNS" }, { "Dns_Tip", "প্রোভাইডারের DNS সমস্যা এড়িয়ে চলে।" },
            { "Advanced_Title", "ফিল্টার" }, { "Quic_Label", "QUIC বন্ধ করুন" }, { "Quic_Tip", "TCP ব্যবহারে বাধ্য করে।" },
            { "Reverse_Label", "বিপরীত ফ্র্যাগমেন্ট" }, { "Reverse_Tip", "HTTPS-এর জন্য ভিন্ন পদ্ধতি।" },
            { "Manual_Btn", "ম্যানুয়াল" }, { "Reset_Btn", "রিসেট" }, { "Apply_Btn", "প্রয়োগ" },
            { "Ask_Exit", "আপনি কি করতে চান?" }, { "Exit_Exit", "বাহির" }, { "Exit_Hide", "লুকান" }, { "Exit_Cancel", "বাতিল" },
            { "Toast_Applied", "✓ সংরক্ষিত!" }, { "Language_Title", "ভাষা" },
            { "Blur_Label", "ব্লার ইফেক্ট" }, { "Boot_Label", "বুট চালু করুন" }, { "AutoStart_Label", "অটো-স্টার্ট" },
            { "Unsaved_Msg", "অসংরক্ষিত পরিবর্তন!" }, { "Discard_Btn", "বাতিল" },
            { "About_Title", "সম্পর্কে" }, { "Tray_Show", "দেখান" }, { "Tray_Exit", "বাহির" },
            { "Tray_Start", "মোড: চালু" }, { "Tray_Stop", "মোড: বন্ধ" },
            { "Reset_Msg", "সব রিসেট করবেন?" }, { "Reset_Confirm", "হ্যাঁ" }
        }},
        { "ur", new Dictionary<string, string> {
            { "Status_Off", "بند" }, { "Status_Running", "جاری" },
            { "Settings_Title", "ترتیبات" }, { "Profile_Title", "پروفائل" }, { "Profile_Tip", "پیکٹ کے ٹکڑے کرنے کا طریقہ۔ موڈ 5 بہترین ہے۔" },
            { "Dns_Title", "DNS انکرپشن" }, { "Dns_Tip", "کمپنی کی DNS پابندیاں ختم کرتا ہے۔" },
            { "Advanced_Title", "فلٹرز" }, { "Quic_Label", "QUIC بند کریں" }, { "Quic_Tip", "سائٹوں کو TCP پر مجبور کرتا ہے۔" },
            { "Reverse_Label", "ریورس ٹکڑے" }, { "Reverse_Tip", "HTTPS کے لیے مختلف ترتیب۔" },
            { "Manual_Btn", "خود سے" }, { "Reset_Btn", "ری سیٹ" }, { "Apply_Btn", "جاری کریں" },
            { "Ask_Exit", "آپ کیا کرنا چاہتے ہیں؟" }, { "Exit_Exit", "بند کریں" }, { "Exit_Hide", "چھپائیں" }, { "Exit_Cancel", "منسوخ" },
            { "Toast_Applied", "✓ مکمل ہوا!" }, { "Language_Title", "زبانیں" },
            { "Blur_Label", "دھندلا اثر" }, { "Boot_Label", "کمپیوٹر کے ساتھ شروع" }, { "AutoStart_Label", "خودکار آغاز" },
            { "Unsaved_Msg", "غیر محفوظ شدہ تبدیلی!" }, { "Discard_Btn", "چھوڑ دیں" },
            { "About_Title", "بارے میں" }, { "Tray_Show", "دکھائیں" }, { "Tray_Exit", "بند کریں" },
            { "Tray_Start", "حالت: آن" }, { "Tray_Stop", "حالت: آف" },
            { "Reset_Msg", "سب ری سیٹ کریں؟" }, { "Reset_Confirm", "ہاں" }
        }},
        { "ta", new Dictionary<string, string> {
            { "Status_Off", "நிறுத்தப்பட்டது" }, { "Status_Running", "இயங்குகிறது" },
            { "Settings_Title", "அமைப்புகள்" }, { "Profile_Title", "சுயவிவரம்" }, { "Profile_Tip", "தரவு துண்டாக்கத்தை தீர்மானிக்கிறது. பயன்முறை 5 சிறந்தது." },
            { "Dns_Title", "DNS குறியாக்க" }, { "Dns_Tip", "ISP DNS சிக்கல்களை தவிர்க்கிறது." },
            { "Advanced_Title", "வடிகட்டிகள்" }, { "Quic_Label", "QUIC-ஐ தவிர்" }, { "Quic_Tip", "தளங்களை TCP பயன்படுத்த கட்டாயப்படுத்துகிறது." },
            { "Reverse_Label", "தலைகீழ் துண்டாக்கு" }, { "Reverse_Tip", "HTTPS-க்கான புதிய முறை." },
            { "Manual_Btn", "கைமுறை" }, { "Reset_Btn", "மீட்டமை" }, { "Apply_Btn", "அமல்படுத்து" },
            { "Ask_Exit", "என்ன செய்ய வேண்டும்?" }, { "Exit_Exit", "வெளியேறு" }, { "Exit_Hide", "மறை" }, { "Exit_Cancel", "ரத்து" },
            { "Toast_Applied", "✓ அமல்படுத்தப்பட்டது!" }, { "Language_Title", "மொழிகள்" },
            { "Blur_Label", "மங்கல் விளைவு" }, { "Boot_Label", "தானாக தொடங்கு" }, { "AutoStart_Label", "சேவை தொடங்கு" },
            { "Unsaved_Msg", "மாற்றங்கள் சேமிக்கப்படவில்லை!" }, { "Discard_Btn", "விலக்கு" },
            { "About_Title", "பற்றி" }, { "Tray_Show", "காண்பி" }, { "Tray_Exit", "வெளியேறு" },
            { "Tray_Start", "நிலை: ஆன்" }, { "Tray_Stop", "நிலை: ஆஃப்" },
            { "Reset_Msg", "அனைத்தையும் மீட்டமைக்கவா?" }, { "Reset_Confirm", "ஆம்" }
        }},
        { "te", new Dictionary<string, string> {
            { "Status_Off", "ఆపివేయబడింది" }, { "Status_Running", "నడుస్తోంది" },
            { "Settings_Title", "సెట్టింగులు" }, { "Profile_Title", "ప్రొఫైల్" }, { "Profile_Tip", "ప్యాకెట్ విభజన నిర్ణయిస్తుంది. మోడ్ 5 సముచితం." },
            { "Dns_Title", "DNS ఎన్క్రిప్షన్" }, { "Dns_Tip", "ISP DNS అడ్డంకులను తొలగిస్తుంది." },
            { "Advanced_Title", "ఫిల్టర్లు" }, { "Quic_Label", "QUIC నిలిపివేయి" }, { "Quic_Tip", "TCP వాడమని బలవంతం చేస్తుంది." },
            { "Reverse_Label", "రివర్స్ బాక్స్" }, { "Reverse_Tip", "HTTPS కోసం కొత్త పద్ధతి." },
            { "Manual_Btn", "మ్యాన్యువల్" }, { "Reset_Btn", "రీసెట్" }, { "Apply_Btn", "వర్తింపజేయి" },
            { "Ask_Exit", "ఏం చేయాలి?" }, { "Exit_Exit", "నిష్క్రమించు" }, { "Exit_Hide", "దాచు" }, { "Exit_Cancel", "రద్దు" },
            { "Toast_Applied", "✓ వర్తించబడింది!" }, { "Language_Title", "భాషలు" },
            { "Blur_Label", "బ్లర్ ఎఫెక్ట్" }, { "Boot_Label", "బూట్ తో ఆరంభించు" }, { "AutoStart_Label", "ఆటో-స్టార్ట్" },
            { "Unsaved_Msg", "మార్పులు సేవ్ కాలేదు!" }, { "Discard_Btn", "వదిలేయి" },
            { "About_Title", "గురించి" }, { "Tray_Show", "చూపించు" }, { "Tray_Exit", "ముగించు" },
            { "Tray_Start", "స్థితి: ఆన్" }, { "Tray_Stop", "స్థితి: ఆఫ్" },
            { "Reset_Msg", "మొత్తం రీసెట్ చేయాలా?" }, { "Reset_Confirm", "అవును" }
        }},
        { "mr", new Dictionary<string, string> {
            { "Status_Off", "बंद" }, { "Status_Running", "चालू आहे" },
            { "Settings_Title", "सेटिंग्ज" }, { "Profile_Title", "प्रोफाइल" }, { "Profile_Tip", "पॅकेट विखंडन ठरवते. मोड ५ समतोल आहे." },
            { "Dns_Title", "एनक्रिप्टेड DNS" }, { "Dns_Tip", "ISP-स्तरावरील DNS फेरफार बायपास करते." },
            { "Advanced_Title", "फिल्टर्स" }, { "Quic_Label", "QUIC बंद करा" }, { "Quic_Tip", "TCP वापरण्यास भाग पाडते." },
            { "Reverse_Label", "रिव्हर्स फ्रॅग" }, { "Reverse_Tip", "HTTPS साठी वेगळा पॅकेट क्रम." },
            { "Manual_Btn", "मॅन्युअल" }, { "Reset_Btn", "रीसेट" }, { "Apply_Btn", "लागू करा" },
            { "Ask_Exit", "काय करायचे आहे?" }, { "Exit_Exit", "बाहेर पडा" }, { "Exit_Hide", "लपवा" }, { "Exit_Cancel", "रद्द करा" },
            { "Toast_Applied", "✓ लागू झाले!" }, { "Language_Title", "भाषा" },
            { "Blur_Label", "ब्लर प्रभाव" }, { "Boot_Label", "बूटवर सुरू करा" }, { "AutoStart_Label", "ऑटो-स्टार्ट" },
            { "Unsaved_Msg", "बदल सेव्ह केले नाहीत!" }, { "Discard_Btn", "रद्द करा" },
            { "About_Title", "माहिती" }, { "Tray_Show", "दाखवा" }, { "Tray_Exit", "बंद" },
            { "Tray_Start", "स्थिती: ऑन" }, { "Tray_Stop", "स्थिती: ऑफ" },
            { "Reset_Msg", "सर्वकाही रीसेट करायचे?" }, { "Reset_Confirm", "हो" }
        }},
        { "gu", new Dictionary<string, string> {
            { "Status_Off", "બંધ" }, { "Status_Running", "ચાલુ" },
            { "Settings_Title", "સેટિંગ્સ" }, { "Profile_Title", "પ્રોફાઇલ" }, { "Profile_Tip", "પેકેટ વિભાજન નક્કી કરે છે. મોડ ૫ સંતુલિત છે." },
            { "Dns_Title", "એનક્રિપ્ટેડ DNS" }, { "Dns_Tip", "ઇન્ટરનેટ પ્રદાતાની DNS સમસ્યાઓ દૂર કરે છે." },
            { "Advanced_Title", "ફિલ્ટર્સ" }, { "Quic_Label", "QUIC બંધ કરો" }, { "Quic_Tip", "સાઇટ્સને TCP વાપરવા દબાણ કરે છે." },
            { "Reverse_Label", "રિવર્સ ફ્રેગમેન્ટ" }, { "Reverse_Tip", "HTTPS માટે અલગ રીત." },
            { "Manual_Btn", "મેન્યુઅલ" }, { "Reset_Btn", "રીસેટ" }, { "Apply_Btn", "લાગુ કરો" },
            { "Ask_Exit", "શું કરવું છે?" }, { "Exit_Exit", "બહાર નીકળો" }, { "Exit_Hide", "છુપાવો" }, { "Exit_Cancel", "રદ કરો" },
            { "Toast_Applied", "✓ લાગુ થઈ ગયું!" }, { "Language_Title", "ભાષાઓ" },
            { "Blur_Label", "બ્લર ઇફેક્ટ" }, { "Boot_Label", "બૂટ પર શરૂ કરો" }, { "AutoStart_Label", "ઓટો-સ્ટાર્ટ" },
            { "Unsaved_Msg", "બદલાવ સેવ થયા નથી!" }, { "Discard_Btn", "રદ કરો" },
            { "About_Title", "વિશે" }, { "Tray_Show", "બતાવો" }, { "Tray_Exit", "બહાર નીકળો" },
            { "Tray_Start", "સ્થિતિ: ઓન" }, { "Tray_Stop", "સ્થિતિ: ઓફ" },
            { "Reset_Msg", "બધું રીસેટ કરવું છે?" }, { "Reset_Confirm", "હા" }
        }},
        { "kn", new Dictionary<string, string> {
            { "Status_Off", "ಸ್ಥಗಿತ" }, { "Status_Running", "ಚಾಲನೆಯಲ್ಲಿದೆ" },
            { "Settings_Title", "ಸೆಟ್ಟಿಂಗ್ಸ್" }, { "Profile_Title", "ಪ್ರೊಫೈಲ್" }, { "Profile_Tip", "ವಿಭಜನೆಯನ್ನು ನಿರ್ಧರಿಸುತ್ತದೆ. ಮೋಡ್ 5 ಉತ್ತಮ." },
            { "Dns_Title", "ಎನ್ಕ್ರಿಪ್ಟ್ ಮಾಡಿದ DNS" }, { "Dns_Tip", "ISP DNS ಕುಶಲತೆಯನ್ನು ತಪ್ಪಿಸುತ್ತದೆ." },
            { "Advanced_Title", "ಫಿಲ್ಟರ್‌ಗಳು" }, { "Quic_Label", "QUIC ನಿಷ್ಕ್ರಿಯಗೊಳಿಸಿ" }, { "Quic_Tip", "TCP ಬಳಸಲು ಒತ್ತಾಯಿಸುತ್ತದೆ." },
            { "Reverse_Label", "ರಿವರ್ಸ್ ಫ್ರಾಗ್" }, { "Reverse_Tip", "HTTPS ಗಾಗಿ ವಿಭಿನ್ನ ಕ್ರಮ." },
            { "Manual_Btn", "ಮ್ಯಾನ್ಯುವಲ್" }, { "Reset_Btn", "ರೀಸೆಟ್" }, { "Apply_Btn", "ಅನ್ವಯಿಸು" },
            { "Ask_Exit", "ಏನು ಮಾಡಬೇಕು?" }, { "Exit_Exit", "ನಿರ್ಗಮಿಸಿ" }, { "Exit_Hide", "ಮರೆಮಾಡಿ" }, { "Exit_Cancel", "ರದ್ದು" },
            { "Toast_Applied", "✓ ಅನ್ವಯಿಸಲಾಗಿದೆ!" }, { "Language_Title", "ಭಾಷೆಗಳು" },
            { "Blur_Label", "ಬ್ಲರ್ ಎಫೆಕ್ಟ್" }, { "Boot_Label", "ಬೂಟ್‌ನಲ್ಲಿ ಪ್ರಾರಂಭಿಸಿ" }, { "AutoStart_Label", "ಸ್ವಯಂಚಾಲಿತ ಚಾಲನೆ" },
            { "Unsaved_Msg", "ಉಳಿಸದ ಬದಲಾವಣೆಗಳು!" }, { "Discard_Btn", "ಬಿಟ್ಟುಬಿಡಿ" },
            { "About_Title", "ಕುರಿತು" }, { "Tray_Show", "ತೋರಿಸು" }, { "Tray_Exit", "ನಿರ್ಗಮಿಸಿ" },
            { "Tray_Start", "ಸ್ಥಿತಿ: ಆನ್" }, { "Tray_Stop", "ಸ್ಥಿತಿ: ಆಫ್" },
            { "Reset_Msg", "ಎಲ್ಲವನ್ನೂ ಮರುಹೊಂದಿಸಿ?" }, { "Reset_Confirm", "ಹೌದು" }
        }},
        { "ml", new Dictionary<string, string> {
            { "Status_Off", "ഓൺ അല്ല" }, { "Status_Running", "പ്രവർത്തിക്കുന്നു" },
            { "Settings_Title", "ക്രമീകരണങ്ങൾ" }, { "Profile_Title", "പ്രൊഫൈൽ" }, { "Profile_Tip", "വിഘടനത്തെ നിർണ്ണയിക്കുന്നു. മോഡ് 5 ഉചിതം." },
            { "Dns_Title", "എൻക്രിപ്റ്റ് ചെയ്ത DNS" }, { "Dns_Tip", "ISP നിയന്ത്രണങ്ങൾ മറികടക്കുന്നു." },
            { "Advanced_Title", "ഫിൽട്ടറുകൾ" }, { "Quic_Label", "QUIC നിർത്തുക" }, { "Quic_Tip", "TCP ഉപയോഗിക്കാൻ നിർബന്ധിക്കുന്നു." },
            { "Reverse_Label", "റിവേഴ്സ് ഫ്രാഗ്" }, { "Reverse_Tip", "HTTPS-നായി പുതിയ ക്രമം." },
            { "Manual_Btn", "മാനുവൽ" }, { "Reset_Btn", "റീസെറ്റ്" }, { "Apply_Btn", "പ്രയോഗിക്കുക" },
            { "Ask_Exit", "എന്തു വേണം?" }, { "Exit_Exit", "പുറത്തുകടക്കുക" }, { "Exit_Hide", "മറയ്ക്കുക" }, { "Exit_Cancel", "റദ്ദാക്കുക" },
            { "Toast_Applied", "✓ പ്രയോഗിച്ചു!" }, { "Language_Title", "ഭാഷകൾ" },
            { "Blur_Label", "മങ്ങൽ ഇഫക്റ്റ്" }, { "Boot_Label", "ബൂട്ടിൽ തുടങ്ങുക" }, { "AutoStart_Label", "ഓട്ടോ-സ്റ്റാർട്ട്" },
            { "Unsaved_Msg", "മാറ്റങ്ങൾ സേവ് ചെയ്തിട്ടില്ല!" }, { "Discard_Btn", "ഉപേക്ഷിക്കുക" },
            { "About_Title", "വിവരങ്ങൾ" }, { "Tray_Show", "കാണിക്കുക" }, { "Tray_Exit", "പുറത്ത്" },
            { "Tray_Start", "നില: ഓൺ" }, { "Tray_Stop", "നില: ഓഫ്" },
            { "Reset_Msg", "റീസെറ്റ് ചെയ്യണോ?" }, { "Reset_Confirm", "അതെ" }
        }},
        { "pa", new Dictionary<string, string> {
            { "Status_Off", "ਬੰਦ" }, { "Status_Running", "ਚੱਲ ਰਿਹਾ ਹੈ" },
            { "Settings_Title", "ਸੈਟਿੰਗਾਂ" }, { "Profile_Title", "ਪ੍ਰੋਫਾਈਲ" }, { "Profile_Tip", "ਪੈਕੇਟ ਫ੍ਰੈਗਮੈਂਟੇਸ਼ਨ ਨਿਰਧਾਰਤ ਕਰਦਾ ਹੈ। ਮੋਡ 5 ਸੰਤੁਲਿਤ ਹੈ।" },
            { "Dns_Title", "ਇਨਕ੍ਰਿਪਟਡ DNS" }, { "Dns_Tip", "ISP DNS ਹੇਰਾਫੇਰੀ ਨੂੰ ਬਾਈਪਾਸ ਕਰਦਾ ਹੈ।" },
            { "Advanced_Title", "ਫਿਲਟਰ" }, { "Quic_Label", "QUIC ਬੰਦ ਕਰੋ" }, { "Quic_Tip", "ਸਾਈਟਾਂ ਨੂੰ TCP ਦੀ ਵਰਤੋਂ ਕਰਨ ਲਈ ਮਜਬੂਰ ਕਰਦਾ ਹੈ।" },
            { "Reverse_Label", "ਰਿਵਰਸ ਫ੍ਰੈਗ" }, { "Reverse_Tip", "HTTPS ਲਈ ਵੱਖਰਾ ਪੈਕੇਟ ਕ੍ਰਮ।" },
            { "Manual_Btn", "ਮੈਨੂਅਲ" }, { "Reset_Btn", "ਰੀਸੈਟ" }, { "Apply_Btn", "ਲਾਗੂ ਕਰੋ" },
            { "Ask_Exit", "ਕੀ ਕਰਨਾ ਹੈ?" }, { "Exit_Exit", "ਬਾਹਰ ਨਿਕਲੋ" }, { "Exit_Hide", "ਛੁਪਾਓ" }, { "Exit_Cancel", "ਰੱਦ ਕਰੋ" },
            { "Toast_Applied", "✓ ਲਾਗੂ ਕੀਤਾ ਗਿਆ!" }, { "Language_Title", "ਭਾਸ਼ਾਵਾਂ" },
            { "Blur_Label", "ਧੁੰਦਲਾ ਪ੍ਰਭਾਵ" }, { "Boot_Label", "ਬੂਟ 'ਤੇ ਸ਼ੁਰੂ" }, { "AutoStart_Label", "ਆਟੋ-ਸਟਾਰਟ" },
            { "Unsaved_Msg", "ਬਦਲਾਅ ਸੇਵ ਨਹੀਂ ਕੀਤੇ!" }, { "Discard_Btn", "ਛੱਡੋ" },
            { "About_Title", "ਬਾਰੇ" }, { "Tray_Show", "ਦਿਖਾਓ" }, { "Tray_Exit", "ਬਾਹਰ" },
            { "Tray_Start", "ਸਥਿਤੀ: ਚਾਲੂ" }, { "Tray_Stop", "ਸਥਿਤੀ: ਬੰਦ" },
            { "Reset_Msg", "ਰੀਸੈਟ ਕਰੀਏ?" }, { "Reset_Confirm", "ਹਾਂ" }
        }},
        { "tl", new Dictionary<string, string> {
            { "Status_Off", "Naka-off" }, { "Status_Running", "Tumatakbo" },
            { "Settings_Title", "Mga Setting" }, { "Profile_Title", "Profile" }, { "Profile_Tip", "Fragmentasyon ng packet. Balanse ang Mode 5." },
            { "Dns_Title", "Encrypted DNS" }, { "Dns_Tip", "Iniiwasan ang manipulasyon ng ISP DNS." },
            { "Advanced_Title", "Mga Filter" }, { "Quic_Label", "I-disable ang QUIC" }, { "Quic_Tip", "Pinipilit ang TCP." },
            { "Reverse_Label", "Baliktad na Frag" }, { "Reverse_Tip", "Ibang pakakasunod para sa HTTPS." },
            { "Manual_Btn", "Manwal" }, { "Reset_Btn", "I-reset" }, { "Apply_Btn", "I-apply" },
            { "Ask_Exit", "Anong gagawin?" }, { "Exit_Exit", "Lumabas" }, { "Exit_Hide", "Itago" }, { "Exit_Cancel", "Kanselahin" },
            { "Toast_Applied", "✓ Nai-apply na!" }, { "Language_Title", "Wika" },
            { "Blur_Label", "Blur Effect" }, { "Boot_Label", "Auto-start sa Boot" }, { "AutoStart_Label", "Auto-start Serbisyo" },
            { "Unsaved_Msg", "May hindi na-save!" }, { "Discard_Btn", "Itapon" },
            { "About_Title", "Tungkol" }, { "Tray_Show", "Ipakita" }, { "Tray_Exit", "Lumabas" },
            { "Tray_Start", "Status: ON" }, { "Tray_Stop", "Status: OFF" },
            { "Reset_Msg", "I-reset lahat?" }, { "Reset_Confirm", "Sige" }
        }},
        { "kk", new Dictionary<string, string> {
            { "Status_Off", "Өшірулі" }, { "Status_Running", "Жұмыс істеуде" },
            { "Settings_Title", "Баптаулар" }, { "Profile_Title", "Профиль" }, { "Profile_Tip", "Пакет фрагментациясын анықтайды. 5-режим оңтайлы." },
            { "Dns_Title", "Шифрленген DNS" }, { "Dns_Tip", "Провайдердің DNS шектеулерін айналып өтеді." },
            { "Advanced_Title", "Сүзгілер" }, { "Quic_Label", "QUIC өшіру" }, { "Quic_Tip", "Сайттарды TCP қолдануға мәжбүрлейді." },
            { "Reverse_Label", "Кері фрагм." }, { "Reverse_Tip", "HTTPS үшін басқа пакет реті." },
            { "Manual_Btn", "Қолмен" }, { "Reset_Btn", "Тастау" }, { "Apply_Btn", "Қолдану" },
            { "Ask_Exit", "Не істейміз?" }, { "Exit_Exit", "Шығу" }, { "Exit_Hide", "Жасыру" }, { "Exit_Cancel", "Болдырмау" },
            { "Toast_Applied", "✓ Сақталды!" }, { "Language_Title", "Тілдер" },
            { "Blur_Label", "Бұлыңғырлау" }, { "Boot_Label", "Авто-қосылу" }, { "AutoStart_Label", "Сервисті қосу" },
            { "Unsaved_Msg", "Сақталмаған өзгерістер!" }, { "Discard_Btn", "Тастау" },
            { "About_Title", "Туралы" }, { "Tray_Show", "Көрсету" }, { "Tray_Exit", "Шығу" },
            { "Tray_Start", "Күйі: ҚОСУ" }, { "Tray_Stop", "Күйі: ӨШІРУ" },
            { "Reset_Msg", "Барлығын тастау?" }, { "Reset_Confirm", "Иә" }
        }},
        { "uz", new Dictionary<string, string> {
            { "Status_Off", "O'chirilgan" }, { "Status_Running", "Ishlamoqda" },
            { "Settings_Title", "Sozlamalar" }, { "Profile_Title", "Profil" }, { "Profile_Tip", "Paket bo'linishini belgilaydi. 5-holat eng yaxshi." },
            { "Dns_Title", "Shifrlangan DNS" }, { "Dns_Tip", "Provayder DNS cheklovlarini chetlab o'tadi." },
            { "Advanced_Title", "Filtrlar" }, { "Quic_Label", "QUIC-ni o'chirish" }, { "Quic_Tip", "Saytlarni TCP dan foydalanishga majburlaydi." },
            { "Reverse_Label", "Teskari b." }, { "Reverse_Tip", "HTTPS uchun boshqa tartib." },
            { "Manual_Btn", "Qo'lda" }, { "Reset_Btn", "Tashlash" }, { "Apply_Btn", "Saqlash" },
            { "Ask_Exit", "Nima qilmoqchisiz?" }, { "Exit_Exit", "Chiqish" }, { "Exit_Hide", "Yashirish" }, { "Exit_Cancel", "Bekor qilish" },
            { "Toast_Applied", "✓ Saqlandi!" }, { "Language_Title", "Tillar" },
            { "Blur_Label", "Xiralashtirish" }, { "Boot_Label", "Avto-yuklash" }, { "AutoStart_Label", "Avto-xizmat" },
            { "Unsaved_Msg", "Saqlanmagan o'zgarishlar!" }, { "Discard_Btn", "Tashlash" },
            { "About_Title", "Haqida" }, { "Tray_Show", "Ko'rsatish" }, { "Tray_Exit", "Chiqish" },
            { "Tray_Start", "Holat: ON" }, { "Tray_Stop", "Holat: OFF" },
            { "Reset_Msg", "Hammasini tashlaymizmi?" }, { "Reset_Confirm", "Ha" }
        }},
        { "ka", new Dictionary<string, string> {
            { "Status_Off", "გამორთულია" }, { "Status_Running", "მუშაობს" },
            { "Settings_Title", "პარამეტრები" }, { "Profile_Title", "პროფილი" }, { "Profile_Tip", "პაკეტის ფრაგმენტაცია. რეჟიმი 5 ბალანსია." },
            { "Dns_Title", "დაშიფრული DNS" }, { "Dns_Tip", "გვერდს უვლის პროვაიდერის DNS შეზღუდვას." },
            { "Advanced_Title", "ფილტრები" }, { "Quic_Label", "QUIC გამორთვა" }, { "Quic_Tip", "აიძულებს საიტებს გამოიყენონ TCP." },
            { "Reverse_Label", "რევერს ფრაგ." }, { "Reverse_Tip", "სხვა პაკეტების რიგი HTTPS-ისთვის." },
            { "Manual_Btn", "ხელით" }, { "Reset_Btn", "განულება" }, { "Apply_Btn", "შენახვა" },
            { "Ask_Exit", "რა გსურთ?" }, { "Exit_Exit", "გამოსვლა" }, { "Exit_Hide", "დამალვა" }, { "Exit_Cancel", "გაუქმება" },
            { "Toast_Applied", "✓ შენახულია!" }, { "Language_Title", "ენები" },
            { "Blur_Label", "ბუნდოვანი ეფექტი" }, { "Boot_Label", "ავტოჩართვა" }, { "AutoStart_Label", "სერვისის ავტოჩართვა" },
            { "Unsaved_Msg", "შეუნახველი ცვლილებები!" }, { "Discard_Btn", "წაშლა" },
            { "About_Title", "შესახებ" }, { "Tray_Show", "ჩვენება" }, { "Tray_Exit", "გასვლა" },
            { "Tray_Start", "მდგომარეობა: ჩართ" }, { "Tray_Stop", "მდგომარეობა: გამორთ" },
            { "Reset_Msg", "განულდეს ყველაფერი?" }, { "Reset_Confirm", "დიახ" }
        }},
        { "hy", new Dictionary<string, string> {
            { "Status_Off", "Անջատված է" }, { "Status_Running", "Աշխատում է" },
            { "Settings_Title", "Կարգավորումներ" }, { "Profile_Title", "Պրոֆիլ" }, { "Profile_Tip", "Սահմանում է ֆրագմենտացիան։ Ռեժիմ 5-ը լավագույնն է։" },
            { "Dns_Title", "Գաղտնագրված DNS" }, { "Dns_Tip", "Շրջանցում է մատակարարի DNS խարդախությունները։" },
            { "Advanced_Title", "Ֆիլտրեր" }, { "Quic_Label", "Անջատել QUIC" }, { "Quic_Tip", "Ստիպում է օգտագործել TCP:" },
            { "Reverse_Label", "Ռևերս ֆրագ․" }, { "Reverse_Tip", "Փաթեթների այլ հերթականություն HTTPS-ի համար։" },
            { "Manual_Btn", "Ձեռքով" }, { "Reset_Btn", "Վերականգնել" }, { "Apply_Btn", "Կիրառել" },
            { "Ask_Exit", "Ի՞նչ անել։" }, { "Exit_Exit", "Ելք" }, { "Exit_Hide", "Թաքցնել" }, { "Exit_Cancel", "Չեղարկել" },
            { "Toast_Applied", "✓ Կիրառված է!" }, { "Language_Title", "Լեզուներ" },
            { "Blur_Label", "Աղոտության էֆեկտ" }, { "Boot_Label", "Ավտոմատ միացում" }, { "AutoStart_Label", "Ծառայության միացում" },
            { "Unsaved_Msg", "Չպահպանված փոփոխություններ!" }, { "Discard_Btn", "Չեղարկել" },
            { "About_Title", "Մասին" }, { "Tray_Show", "Ցուցադրել" }, { "Tray_Exit", "Ելք" },
            { "Tray_Start", "Ռեժիմ։ Միացված" }, { "Tray_Stop", "Ռեժիմ։ Անջատված" },
            { "Reset_Msg", "Վերականգնե՞լ ամբողջը։" }, { "Reset_Confirm", "Այո" }
        }},
        { "sq", new Dictionary<string, string> {
            { "Status_Off", "Fikur" }, { "Status_Running", "Po punon" },
            { "Settings_Title", "Cilësimet" }, { "Profile_Title", "Profili" }, { "Profile_Tip", "Përcakton fragmentimin. Mënyra 5 është e balancuar." },
            { "Dns_Title", "DNS e Kriptuar" }, { "Dns_Tip", "Anashkalon manipulimin DNS të ofruesit." },
            { "Advanced_Title", "Filtrat" }, { "Quic_Label", "Fikni QUIC" }, { "Quic_Tip", "Detyron faqet të përdorin TCP." },
            { "Reverse_Label", "Fragmente mbrapsht" }, { "Reverse_Tip", "Renditje tjetër paketash për HTTPS." },
            { "Manual_Btn", "Manualisht" }, { "Reset_Btn", "Rikthe" }, { "Apply_Btn", "Apliko" },
            { "Ask_Exit", "Çfarë doni të bëni?" }, { "Exit_Exit", "Dil" }, { "Exit_Hide", "Fsheh" }, { "Exit_Cancel", "Anulo" },
            { "Toast_Applied", "✓ U aplikua!" }, { "Language_Title", "Gjuhët" },
            { "Blur_Label", "Efekti flou" }, { "Boot_Label", "Nisje me sistemin" }, { "AutoStart_Label", "Auto-start shërbimi" },
            { "Unsaved_Msg", "Ndryshime të papasave!" }, { "Discard_Btn", "Hidhe" },
            { "About_Title", "Rreth" }, { "Tray_Show", "Trego" }, { "Tray_Exit", "Dil" },
            { "Tray_Start", "Statusi: AKTIV" }, { "Tray_Stop", "Statusi: FIKUR" },
            { "Reset_Msg", "Rikthe cilësimet?" }, { "Reset_Confirm", "Po" }
        }},
        { "et", new Dictionary<string, string> {
            { "Status_Off", "Väljas" }, { "Status_Running", "Töötab" },
            { "Settings_Title", "Seaded" }, { "Profile_Title", "Profiil" }, { "Profile_Tip", "Määrab fragmentatsiooni. Režiim 5 on tasakaalus." },
            { "Dns_Title", "Krüpteeritud DNS" }, { "Dns_Tip", "Mööda ISP DNS manipuleerimisest." },
            { "Advanced_Title", "Filtrid" }, { "Quic_Label", "Keela QUIC" }, { "Quic_Tip", "Sunnib TCP kasutama." },
            { "Reverse_Label", "Revers frag." }, { "Reverse_Tip", "Teistsugune järjekord HTTPS-ile." },
            { "Manual_Btn", "Manuaalne" }, { "Reset_Btn", "Lähtesta" }, { "Apply_Btn", "Rakenda" },
            { "Ask_Exit", "Mida soovid teha?" }, { "Exit_Exit", "Välju" }, { "Exit_Hide", "Peida" }, { "Exit_Cancel", "Tühista" },
            { "Toast_Applied", "✓ Rakendatud!" }, { "Language_Title", "Keeled" },
            { "Blur_Label", "Udu-efekt" }, { "Boot_Label", "Käivitu süsteemiga" }, { "AutoStart_Label", "Automaatne teenus" },
            { "Unsaved_Msg", "Salvestamata muudatused!" }, { "Discard_Btn", "Hülga" },
            { "About_Title", "Info" }, { "Tray_Show", "Näita" }, { "Tray_Exit", "Lõpeta" },
            { "Tray_Start", "Olek: SEES" }, { "Tray_Stop", "Olek: VÄLJAS" },
            { "Reset_Msg", "Lähtesta kõik?" }, { "Reset_Confirm", "Jah" }
        }},
        { "lv", new Dictionary<string, string> {
            { "Status_Off", "Izslēgts" }, { "Status_Running", "Darbojas" },
            { "Settings_Title", "Iestatījumi" }, { "Profile_Title", "Profils" }, { "Profile_Tip", "Fragmentācija. 5. režīms ir stabilākais." },
            { "Dns_Title", "Šifrēts DNS" }, { "Dns_Tip", "Apiet pakalpojumu sniedzēja DNS blokus." },
            { "Advanced_Title", "Filtri" }, { "Quic_Label", "Izslēgt QUIC" }, { "Quic_Tip", "Spiež lietot TCP." },
            { "Reverse_Label", "Reversā fragm." }, { "Reverse_Tip", "Cita pakotņu secība HTTPS." },
            { "Manual_Btn", "Manuāli" }, { "Reset_Btn", "Atiestatīt" }, { "Apply_Btn", "Saglabāt" },
            { "Ask_Exit", "Ko darīt?" }, { "Exit_Exit", "Iziet" }, { "Exit_Hide", "Paslēpt" }, { "Exit_Cancel", "Atcelt" },
            { "Toast_Applied", "✓ Saglabāts!" }, { "Language_Title", "Valodas" },
            { "Blur_Label", "Blur efekts" }, { "Boot_Label", "Auto-starts" }, { "AutoStart_Label", "Auto-dienests" },
            { "Unsaved_Msg", "Nesaglabātas izmaiņas!" }, { "Discard_Btn", "Atmest" },
            { "About_Title", "Par" }, { "Tray_Show", "Rādīt" }, { "Tray_Exit", "Beigt" },
            { "Tray_Start", "Statuss: ON" }, { "Tray_Stop", "Statuss: OFF" },
            { "Reset_Msg", "Atiestatīt visu?" }, { "Reset_Confirm", "Jā" }
        }},
        { "lt", new Dictionary<string, string> {
            { "Status_Off", "Išjungta" }, { "Status_Running", "Veikia" },
            { "Settings_Title", "Nustatymai" }, { "Profile_Title", "Profilis" }, { "Profile_Tip", "Fragmentavimo nustatymas. 5 režimas yra subalansuotas." },
            { "Dns_Title", "Šifruotas DNS" }, { "Dns_Tip", "Apeina tiekėjo DNS ribojimus." },
            { "Advanced_Title", "Filtrai" }, { "Quic_Label", "Išjungti QUIC" }, { "Quic_Tip", "Verčia naudoti TCP." },
            { "Reverse_Label", "Atvirkštinė frag." }, { "Reverse_Tip", "Kita paketų eilė HTTPS." },
            { "Manual_Btn", "Rankiniu būdu" }, { "Reset_Btn", "Atstatyti" }, { "Apply_Btn", "Išsaugoti" },
            { "Ask_Exit", "Ką norite daryti?" }, { "Exit_Exit", "Išeiti" }, { "Exit_Hide", "Paslėpti" }, { "Exit_Cancel", "Atšaukti" },
            { "Toast_Applied", "✓ Išsaugota!" }, { "Language_Title", "Kalbos" },
            { "Blur_Label", "Blur efektas" }, { "Boot_Label", "Auto-startas" }, { "AutoStart_Label", "Auto-paslauga" },
            { "Unsaved_Msg", "Nesaugoti pakeitimai!" }, { "Discard_Btn", "Atmesti" },
            { "About_Title", "Apie" }, { "Tray_Show", "Rodyti" }, { "Tray_Exit", "Išeiti" },
            { "Tray_Start", "Būsena: ON" }, { "Tray_Stop", "Būsena: OFF" },
            { "Reset_Msg", "Atstatyti viską?" }, { "Reset_Confirm", "Taip" }
        }}
    };

    public static string Get(string key)
    {
        if (Dictionaries.ContainsKey(CurrentLanguage) && Dictionaries[CurrentLanguage].ContainsKey(key))
            return Dictionaries[CurrentLanguage][key];
        
        if (Dictionaries.ContainsKey("en") && Dictionaries["en"].ContainsKey(key)) 
            return Dictionaries["en"][key];
        
        return key;
    }
}
